### PR TITLE
construct each handler by a custom backend

### LINKED ISSUE #10676: construct each handler by a custom backend
From @desa 's [idea/suggestion](https://github.com/influxdata/platform/pull/1993#discussion_r242705738).

Use a config struct to construct all API handlers.

Benefit:
When we want to add more services or config options to a new handler,
we don't have to modify the function signature and change args of function for all callers.

At present, there is already such a config struct exists, the [http.APIBackend](https://github.com/influxdata/platform/blob/master/http/api_handler.go#L34-L66).

---

## Update [2018-12-28]
Add a custom backend for each handler.

Handlers:
 - [x] BucketHandler        
 - [x] UserHandler          
 - [x] OrgHandler           
 - [x] AuthorizationHandler 
 - [x] DashboardHandler             
 - [x] SourceHandler        
 - [x] MacroHandler         
 - [x] TaskHandler          
 - [x] TelegrafHandler      
 - [x] QueryHandler         
 - [x] WriteHandler         
 - [x] SetupHandler         
 - [x] SessionHandler     
 - [x] MemberHandler       
 - [x] LabelHandler

### PR DESCRIPTION
**Pull request by zhulongcheng**
Closes #10676

_Briefly describe your proposed changes:_

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] http/swagger.yml updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by zhulongcheng** [comment]
Rebased.

**Comment by zhulongcheng** [comment]
@leodido Would you mind taking a look again?

More commits added.
I think it is ready to close #10676

**Comment by goller** [comment]
Hi @zhulongcheng we didn't merge this quite fast enough; sorry!  Would you be able to rebase ?

**Comment by leodido** [comment]
@zhulongcheng I rebased this locally and made some adjustements. Fixing last bits.

**Comment by leodido** [comment]
Closing in favor of #11695.

**Pull request closed without merging**
