### PR TITLE
refactor: automated move of errors and id from root to kit

### PR DESCRIPTION
**Pull request by lesam**
Move `errors.go` to kit/platform/errors, and move `id.go` to kit/platform. This splits some pretty fundamental code out from the crowded root module and makes backports back to 1.x easier.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

**Comment by lesam** [comment]
No changelog / issue for mechanical refactor

**Review by danxmoran — APPROVED** [review]

**Comment by lesam** [comment]
The only manual change was in TestID_GoString, to account for the changed package name.

**Review by danxmoran — CHANGES_REQUESTED** [review]
Thought of something while working on #21085. There are `.tmpl` files that reference `influxdb.Error` and some of the error codes. They'll need to be updated too.

**Comment by danxmoran** [comment]
Superseded by  #21101

**Pull request closed without merging**
