### PR TITLE
Allow multiple Collectd plugin listeners

### PR DESCRIPTION
**Pull request by mengelmann**
- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Related to feature request #2785 "Some services should be able to have multiple instances". Code based on the multiple Graphite listeners.

### CODE REVIEW

**Comment by gunnaraasen** [comment]
@mengelmann Just found this PR after opening up a similar one (https://github.com/influxdata/influxdb/pull/6228). This looks good to me but will need a review by a couple of the core devs.

**Comment by joelegasse** [comment]
This would conflict with #6228, which does a little bit more cleanup and includes an additional service.

**Comment by mengelmann** [comment]
@joelegasse sure, if PR #6228 has better code than this one and it's more likely to be merged, then it's fine with me. 

We have use case that needs multiple collectd listeners and having it in the upstream version without patching is the most important for me, regardless whose PR is used :)

**Comment by jsternberg** [comment]
It looks like #6228 was merged instead. I'm going to close this PR. Thanks for contributing anyway!

**Pull request closed without merging**
