### PR TITLE
lock auth properly

### PR DESCRIPTION
**Pull request by rubycut**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by rubycut** [comment]
Fixes #6760

**Comment by jwilder** [comment]
The `c.cacheData.Clone()` calls is unnecessary and can be very expensive to run on every request.  That should be removed.

I think you can simplify the locking with the following.  

```diff
diff --git a/services/meta/client.go b/services/meta/client.go
index 8dad1d6..4f79ef9 100644
--- a/services/meta/client.go
+++ b/services/meta/client.go
@@ -569,19 +569,20 @@ func (c *Client) AdminUserExists() bool {
 }

 func (c *Client) Authenticate(username, password string) (*UserInfo, error) {
-       c.mu.RLock()
-       defer c.mu.RUnlock()
-
-       data := c.cacheData.Clone()
-
        // Find user.
-       userInfo := data.User(username)
+       c.mu.RLock()
+       userInfo := c.cacheData.User(username)
+       c.mu.RUnlock()
        if userInfo == nil {
                return nil, ErrUserNotFound
        }

        // Check the local auth cache first.
-       if au, ok := c.authCache[username]; ok {
+       c.mu.RLock()
+       au, ok := c.authCache[username]
+       c.mu.RUnlock()
+
+       if ok {
                // verify the password using the cached salt and hash
                if bytes.Equal(c.hashWithSalt(au.salt, password), au.hash) {
                        return userInfo, nil
@@ -600,7 +601,9 @@ func (c *Client) Authenticate(username, password string) (*UserInfo, error) {
        if err != nil {
                return nil, err
        }
+       c.mu.Lock()
        c.authCache[username] = authUser{salt: salt, hash: hashed, bhash: userInfo.Hash}
+       c.mu.Unlock()

        return userInfo, nil
 }
```

**Comment by rubycut** [comment]
@jwilder , this actually worked, with this patch, database was running for 7 hours and then crashed, see #6782 but I don't think it's related to this issue.

**Comment by jwilder** [comment]
👍 Thanks @rubycut!

**Pull request merged**
