### PR TITLE
[WIP] Ensure measurement dropped when no more series

### LINKED ISSUE #6498: [0.13] Possible issue with DROP SERIES
### Bug report

InfluxDB 0.13, Ubuntu

As expected, when I `DELETE` a series, the series still shows up when I execute `SHOW SERIES` and the series' measurement shows up when I execute `SHOW MEASUREMENTS`.

However, when I `DROP` a series, the series' measurement shows up when I execute `SHOW MEASUREMENTS`, but not when I run `SHOW SERIES`. I would expect that `SHOW MEASUREMENTS` would not return the series' measurement.

1. Create a database and write to two measurements:

```
> create database test
> insert for_drop_series value=2
> insert for_delete_series value=200
> show measurements
name: measurements
------------------
name
for_delete_series
for_drop_series

> show series
key
for_delete_series
for_drop_series
```

2. Run `DELETE SERIES` and `DROP SERIES`:

```
> drop series from for_drop_series
> delete from for_delete_series
```

3. Execute `SHOW MEASUREMENTS` and `SHOW SERIES`:

```
> show measurements
name: measurements
------------------
name
for_delete_series
for_drop_series

> show series
key
for_delete_series
```

I'd expect `for_drop_series` not to show up with `SHOW MEASUREMENTS`.

Not completely related, but I expected the delete series syntax to be `DELETE SERIES FROM` instead of `DELETE FROM`.

### PR DESCRIPTION
**Pull request by e-dard**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Fixes #6498

### CODE REVIEW

**Comment by jwilder** [comment]
We need this same fix for `DeleteSeriesRange` too.

**Comment by e-dard** [comment]
@jwilder hmmm. I think the issue is that when `DELETE SERIES` is issued, the `TSDB` is instructed to delete series data but not to touch any meta data, which means neither the `series` or the `measurement` will be removed from the index (if I'm following correctly).

Seems like there is already a pre-existing issue here. The determining factor for when `DatabaseIndex.DropSeries` is called should be when there is no more points in the series, not whether `DROP SERIES` or `DELETE SERIES` was issued. 

My thinking would be to remove the `dropMeta bool` parameter from `Store.DeleteSeries`, and instead determine inside that method whether or not `DatabaseIndex.DropSeries` needs to be called.

Thoughts?

**Comment by jwilder** [comment]
@e-dard Yeah, that sounds right.  

I was referring to this [issue](https://github.com/influxdata/influxdb/pull/6484#issuecomment-215265032) related to `delete series`.  If you delete the whole series, it currently leaves the series in the index.  After you restart, it disappears which is confusing.  In this case, it should remove the series from the index too so that the behavior is the same before and after a restart.

Related to this PR, if you fully delete the series _and_ it was the last series for the measurement, we should also remove the measurement from the index too because it would also disappear after a restart.

**Comment by e-dard** [comment]
LGTM 👍  :shipit:

**Pull request merged**
