### PR TITLE
fix: support gzipped responses in the legacy handler

### LINKED ISSUE #23805: The legacy handler doesn't support gzipped responses compared to 1.x versions
__Steps to reproduce:__

1. Run a query on the legacy route `/query` with `Accept-Encoding: gzip`
3. View the provided HTTP response, which is not compressed.

__Expected behavior:__

When the client indicates that it supports gzipped responses, the legacy handler should provide compressed content with a `Content-Encoding: gzip` header, as it was the case in influxdb 1.x.
 
__Actual behavior:__
None of the responses coming from the legacy handler are compressed, which can have a huge impact on the consumed bandwidth.

InfluxDB 2.4.0 :

```
$ curl -i -u "xxxx:xxxx" http://localhost:8086/query --data-urlencode "db=mydb" --data-urlencode 'q=SELECT * FROM mydata' --compressed

HTTP/1.1 200 OK
Content-Type: application/json
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.4.0
Date: Sun, 16 Oct 2022 14:48:54 GMT
Transfer-Encoding: chunked
```

Compared to InfluxDB 1.8.10 :

```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
Request-Id: 99f3c990-4d61-11ed-bccb-cae8df9b3012
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.10
X-Request-Id: 99f3c990-4d61-11ed-bccb-cae8df9b3012
Date: Sun, 16 Oct 2022 14:48:30 GMT
Transfer-Encoding: chunked
```

__Environment info:__

* InfluxDB version: InfluxDB v2.4.0 (git: de247bab08) build_date: 2022-08-18T19:41:15Z

### PR DESCRIPTION
**Pull request by cbonte**
- Closes #23805
### Required checklist
- [x] Sample config files updated (both `/etc` folder and `NewDemoConfig` methods) (influxdb and plutonium)
- [x] openapi swagger.yml updated (if modified API) - link openapi PR
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### Description
This PR enables gzip compression on the legacy handler, as it was in influxdb v1.x versions.

### Context
The goal is to reduce bandwidth usage when possible.

### Note for reviewers:
Check the semantic commit type:
 - Feat: a feature with user-visible changes
 - Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
 - Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
 - Build: build script changes, CI config changes, build tool updates
 - Refactor: non-user-visible refactoring
 - Check the PR title: we should be able to put this as a one-liner in the release notes

### CODE REVIEW

**Comment by cbonte** [comment]
I think the openapi swagger file doesn't require an update.

**Comment by jeffreyssmith2nd** [comment]
Hi @cbonte, thanks for the contribution! I believe the Semantic PR check is failing because your branch needs to be rebased against the latest master. Can you give that try and re-push?

**Comment by cbonte** [comment]
ok @jeffreyssmith2nd, the PR is rebased. But some tests failed due to a timeout (test-race took more than 10 minutes).

**Comment by jeffreyssmith2nd** [comment]
> ok @jeffreyssmith2nd, the PR is rebased. But some tests failed due to a timeout (test-race took more than 10 minutes).

Thanks! Sometimes that happens due to some CI instability, I've rekicked CI and will keep an eye on it.

**Review by jeffreyssmith2nd — APPROVED** [review]

**Pull request merged**
