### PR TITLE
fix panic in transform iterator on division

### PR DESCRIPTION
**Pull request by thbourlove**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [ ] [InfluxQL Spec](https://github.com/influxdata/influxdb/blob/master/influxql/README.md) updated

if left point is nil in division expr, the influxd server would panic. Now check left point before use it. #6377

### CODE REVIEW

**Comment by e-dard** [comment]
LGTM 👍

**Comment by jwilder** [comment]
@jsternberg

**Comment by jsternberg** [comment]
LGTM 👍 

@thbourlove can you rebase and I'll try to merge it before another conflict happens?

**Comment by thbourlove** [comment]
ping @jsternberg

**Pull request merged**
