### PR TITLE
 Ensure that all waiting WAL writers fsync

### PR DESCRIPTION
**Pull request by e-dard**
This PR considers the notion that the WAL is closed whilst
`scheduleSync` is executing, but while it's waiting on the `select` for the `timerCh`
and `closing` cases. In this scenario, if the `closing` channel is received
on, then `scheduleSync` will return, and no calls to `sync` will be made.
Without the requisite calls to `sync`, it's possible that nothing will
ever be sent on the `syncErr` channels in `writeToLog`, and so `writeToLog`
could block on the final return.

This is most likely to occur when the WAL fsync delay is set to a large value (which means more time spent waiting at the `select` in `scheduleSync`. The WAL fsync delay is controlled via `wal-fsync-delay` in the server configuration.

Possibly helps with [some aspects](https://github.com/influxdata/influxdb/issues/8500#issuecomment-312971606) of #8500.

###### Required for all non-trivial PRs
- [ ] Rebased/mergable
- [ ] Tests pass

### CODE REVIEW

**Comment by jwilder** [comment]
```
--- PASS: TestStore_Cardinality_Compactions_TSI1 (87.06s)
[I] 2017-07-06T14:24:12Z Using data dir: /tmp/influxdb-tsdb-016084994 service=store
fatal error: out of memory

runtime stack:
runtime.throw(0x8459170, 0xd)
	/usr/local/go/src/runtime/panic.go:596 +0x7c
runtime.(*mcache).refill(0xf74e5258, 0x7, 0x97a283b0)
	/usr/local/go/src/runtime/mcache.go:124 +0xe3
runtime.(*mcache).nextFree.func1()
	/usr/local/go/src/runtime/malloc.go:538 +0x28
runtime.systemstack(0x1891aa80)
	/usr/local/go/src/runtime/asm_386.s:337 +0x5e
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132

goroutine 381730 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_386.s:291 fp=0x1892fb40 sp=0x1892fb3c
runtime.(*mcache).nextFree(0xf74e5258, 0x7, 0x18925180, 0x8093150, 0x18925180)
	/usr/local/go/src/runtime/malloc.go:539 +0x9e fp=0x1892fb68 sp=0x1892fb40
runtime.mallocgc(0x60, 0x83e7360, 0x8057201, 0xc884e4e0)
	/usr/local/go/src/runtime/malloc.go:691 +0x642 fp=0x1892fbb8 sp=0x1892fb68
runtime.makeslice(0x83e7360, 0x5f, 0x5f, 0x97a283b0, 0x9, 0x10)
	/usr/local/go/src/runtime/slice.go:54 +0x5d fp=0x1892fbdc sp=0x1892fbb8
github.com/influxdata/influxdb/models.Tags.HashKey(0x97a1de80, 0x5, 0x5, 0xc884ce10, 0xe, 0x10)
	/root/go/src/github.com/influxdata/influxdb/models/points.go:1981 +0x26f fp=0x1892fcb4 sp=0x1892fbdc
github.com/influxdata/influxdb/models.MakeKey(0xc884cdd0, 0xe, 0x10, 0x97a1de80, 0x5, 0x5, 0xc, 0xc8844801, 0x80e3501)
	/root/go/src/github.com/influxdata/influxdb/models/points.go:1484 +0x85 fp=0x1892fcf4 sp=0x1892fcb4
github.com/influxdata/influxdb/models.pointKey(0x3d661350, 0xe, 0x97a1de80, 0x5, 0x5, 0xc8844860, 0xd0f03f25, 0xe, 0x93568ee, 0x8649ac0, ...)
	/root/go/src/github.com/influxdata/influxdb/models/points.go:1274 +0x187 fp=0x1892fde4 sp=0x1892fcf4
github.com/influxdata/influxdb/models.NewPoint(0x3d661350, 0xe, 0x97a1de80, 0x5, 0x5, 0xc8844860, 0xd0f03f25, 0xe, 0x93568ee, 0x8649ac0, ...)
	/root/go/src/github.com/influxdata/influxdb/models/points.go:1231 +0x70 fp=0x1892fe40 sp=0x1892fde4
github.com/influxdata/influxdb/models.MustNewPoint(0x3d661350, 0xe, 0x97a1de80, 0x5, 0x5, 0xc8844860, 0xd0f03f25, 0xe, 0x93568ee, 0x8649ac0, ...)
	/root/go/src/github.com/influxdata/influxdb/models/points.go:1338 +0x6d fp=0x1892fe84 sp=0x1892fe40
github.com/influxdata/influxdb/tsdb_test.testStoreCardinalityCompactions(0x1955af80, 0x8a961708)
	/root/go/src/github.com/influxdata/influxdb/tsdb/store_test.go:719 +0x2d6 fp=0x1892ffb8 sp=0x1892fe84
github.com/influxdata/influxdb/tsdb_test.TestStore_Cardinality_Compactions_Inmem(0x1955af80)
	/root/go/src/github.com/influxdata/influxdb/tsdb/store_test.go:766 +0xac fp=0x1892ffd4 sp=0x1892ffb8
testing.tRunner(0x1955af80, 0x846dab8)
	/usr/local/go/src/testing/testing.go:657 +0x7e fp=0x1892ffe8 sp=0x1892ffd4
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1629 +0x1 fp=0x1892ffec sp=0x1892ffe8
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x242
```

**Comment by e-dard** [comment]
@jwilder as @stuartcarnie mentioned to me—looks like we're calling `sync` on the WAL close anyway, so I think we can close this PR without merging? Or do you think there is value in figuring out why the compaction stuff OOMed?

**Comment by jwilder** [comment]
@e-dard @stuartcarnie I didn't realize `Close` called sync.  Yeah, this PR isn't necessary then.  The panic looks like a transient circle failure.

**Comment by jwilder** [comment]
Closing this since it's already handled in the current code.

**Pull request closed without merging**
