### PR TITLE
build(flux): update flux to v0.194.3

### PR DESCRIPTION
**Pull request by wolffcm**
### Required checklist
- [x] Sample config files updated (both `/etc` folder and `NewDemoConfig` methods) (influxdb and plutonium) (N/A)
- [x] openapi swagger.yml updated (if modified API) - link openapi PR (N/A)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed) 

### Description
This updates OSS 2.0 to the latest Flux version, which includes a fix for https://github.com/influxdata/flux/issues/5415.

### Affected areas (delete section if not relevant):
Fixes bug with Flux function `histogramQuantile`.

### Note for reviewers:
Check the semantic commit type:
 - Feat: a feature with user-visible changes
 - Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
 - Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
 - Build: build script changes, CI config changes, build tool updates
 - Refactor: non-user-visible refactoring
 - Check the PR title: we should be able to put this as a one-liner in the release notes

### CODE REVIEW

**Review by davidby-influx — APPROVED** [review]
LGTM

**Comment by wolffcm** [comment]
@davidby-influx CI seems to be failing due to this:
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/19913/workflows/4ee1a49e-37a0-4de3-b8eb-c1f5098bc837/jobs/1415051

It doesn't seem related to my change. What is the typical action for a failure like this?

**Comment by davidby-influx** [comment]
@bnpfeife - also dragging you into this.

**Comment by jeffreyssmith2nd** [comment]
I believe [this](https://github.com/influxdata/monitor-ci/pull/420) will resolve the issue

**Pull request merged**
