### PR TITLE
build: revert deletion of `influx` CLI code

### PR DESCRIPTION
**Pull request by danxmoran**
(Mostly) reverts #21877

Best reviewed commit-by-commit:
1. d064cf6 is a mostly-clean `git revert`. There were some conflicts in `go.mod` and code under `cmd/influxd` where things got cleaned up after the CLI was deleted; I edited the revert-patch to not change those spots
2. b0bff1d  Bumps the CLI dependency to pull in bugfixes around interactive I/O
3. e66d76c Re-deletes our hacky `go-input`-based functions for interactive I/O, replacing those usages with calls to utilities from the new CLI. This should fix problems users were hitting in powershell
4. 41141e8 Deletes `pkg/csv2lp`, which was copied verbatim to `influx-cli`
5. 932a4a4 Deletes `pkg/jsonnet`, which was copied verbatim to `influx-cli`

### CODE REVIEW

**Comment by danxmoran** [comment]
Ugh, that's probably caused by [this line](https://github.com/influxdata/influx-cli/blob/main/pkg/stdio/interactive.go#L68), which I added to work around [this issue](https://github.com/AlecAivazis/survey/pull/335) while the fix was still unreleased. I'll open an issue in `influx-cli` because it's going to hit there too; hopefully upgrading `survey` and switching `HorizontalAbsolute` to `DownLine` will make it work

**Comment by wbaker85** [comment]
> Ugh, that's probably caused by [this line](https://github.com/influxdata/influx-cli/blob/main/pkg/stdio/interactive.go#L68), which I added to work around [this issue](https://github.com/AlecAivazis/survey/pull/335) while the fix was still unreleased. I'll open an issue in `influx-cli` because it's going to hit there too; hopefully upgrading `survey` and switching `HorizontalAbsolute` to `NextLine` will make it work

Sounds good...definitely a big improvement over the previous version which didn't work at all on powershell!

**Comment by wbaker85** [comment]
Speaking of previous versions...are you going to make any `CHANGELOG` updates with this? There's some bugfixes for sure. Not sure how that will work with the code that fixed the bug being in a separate repo though.

**Comment by danxmoran** [comment]
> are you going to make any CHANGELOG updates with this?

Yes, I'll make a note about fixing the interactive I/O on powershell. I think that'll be the only bugfix from this... other bugs that got fixed in the new `influx-cli` code didn't get ported back here

**Review by wbaker85 — APPROVED** [review]

**Pull request merged**
