### PR TITLE
Remove NaN from query engine

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This pull request removes `math.NaN` returns from float iterators.

/cc @jwilder

### CODE REVIEW

**Comment by jwilder** [comment]
```
--- FAIL: TestShard_CreateIterator (1.01s)
	shard_test.go:208: unexpected point(1): (*influxql.FloatPoint)(0xc208124000)({
		 Name: (string) (len=3) "cpu",
		 Tags: (influxql.Tags) {
		  id: (string) (len=12) "host\x00serverB",
		  m: (map[string]string) (len=1) {
		   (string) (len=4) "host": (string) (len=7) "serverB"
		  }
		 },
		 Time: (int64) 0,
		 Nil: (bool) false,
		 Value: (float64) 25,
		 Aux: ([]interface {}) (len=1 cap=1) {
		  (float64) 0
		 }
		})
```

**Comment by jwilder** [comment]
Should fix #5662

**Comment by benbjohnson** [comment]
Fixed in f7e04ab.

**Comment by jwilder** [comment]
:+1:

**Pull request merged**
