### PR TITLE
ci: run go mod tidy for the promqltests

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by nathanielc** [comment]
Does this imply CI is not normally running tidy and comparing it against the repo?

**Comment by jsternberg** [comment]
It doesn't seem so. I don't think our CI is checking promqltests at all.

**Comment by nathanielc** [comment]
I thought that was integrated when the promql code landed. Can you verify?

**Comment by jsternberg** [comment]
I'm not very familiar with how the tests are run but the only mention to `promqltests` I see in the makefile is `test-promql-e2e` and a simple grep for that returns nothing except for the single line creating the target.

```
jsternberg:[~/g/s/g/i/influxdb] $ (master $=) git grep promqltests
.circleci/config.yml:257:            # filter internal/promqltests because it has special go.mod
.circleci/config.yml:258:            TESTFILES=$(go list ./... | grep -v internal/promqltests | circleci tests split --split-by=timings)
Makefile:147:   cd query/promql/internal/promqltests; go test ./...
query/promql/internal/promqltests/README.md:3:The code under this directory is organized in the go submodule `github.com/influxdata/promqltests`.
query/promql/internal/promqltests/end_to_end_test.go:1:package promqltests
query/promql/internal/promqltests/engine.go:1:package promqltests
query/promql/internal/promqltests/go.mod:1:module github.com/influxdata/promqltests
query/promql/internal/promqltests/helpers.go:1:package promqltests
query/promql/internal/promqltests/tests.go:1:package promqltests
jsternberg:[~/g/s/g/i/influxdb] $ (master $=) git grep test-promql-e2e
Makefile:146:test-promql-e2e:
```

The only thing I do see in there is that there seems to be special code to ensure that `promqltests` get filtered when we split off the unit tests to different executors.

**Pull request merged**
