### PR TITLE
Implement INTEGRAL() to show the sum over time

### PR DESCRIPTION
**Pull request by slamplug**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._

### CODE REVIEW

**Comment by nathanielc** [comment]
@slamplug  I was reviewing this PR today and overall it looks great. I do have one question though about what this is doing.

In the reducer you have this equation:

```
r.current += (r.curr.Value - r.prev.Value)
```
And then return the r.current value which grows as more points are seen.


I expected this to take into account the time of the points as well. Something like:

```
r.current += r.curr.Value * float64((r.curr.Time - r.prev.Time) / r.unit)
```
>NOTE: The above is using a simplistic right-sided sum, using a trapezoid method or something else is much better.

Could you share the use case you had in mind when you implemented this function?

**Comment by slamplug** [comment]
We currently use graphite as a metric store and are keen to move to influx.

One display that we currently make use of is a count of events during a
time period with the count starting at 0 at the start of the time period.

I based the code change loosely on the graphite implementation of the
integral function.

**Comment by nathanielc** [comment]
@slamplug Thanks for the reply. If i understand correctly then you have a series of value that are counters for events. The value of each point is the total number of events since the process(or whatever) started. You want to graph the cumulative number of events starting at a specific time period. In that case your logic makes sense but I would call it `cumsum` for cumulative sum. Also the logic could be simplified to not do the difference and only perform the `cumsum` of the data. Then this query would do what you want, `cumsum(difference(value))`. You could even swap out difference for derivative depending on the use case `cumsum(derivative(value,1s))`. 

Let me know if I have miss understood.

**Comment by jsternberg** [comment]
@slamplug is ok if I use your commits and build on top of them to finish this feature? I think @nathanielc is right about the implementation of integral so I'll add that too so this can act as the opposite of derivative.

**Comment by jsternberg** [comment]
Closing this in favor of #7388. Thank you for the idea. I changed the name to `cumulative_sum()` since this did not calculate the integral, but the cumulative sum. Thanks again!

**Pull request closed without merging**
