### PR TITLE
fix(influx): support days as duration type

### LINKED ISSUE #18639: Influx CLI - allow bucket creation RP in 'd' units (days)
__Proposal:__
Allow for buckets to be created with a retention policy in days "d" units. Note that in 1.x, duration units include days **d** and weeks **w** as well:
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#durations

__Current behavior:__
```
./influx bucket create -n testbucket -r 10d
Error: invalid argument "10d" for "-r, --retention" flag: time: unknown unit d in duration 10d
```

__Desired behavior:__
I would like for the "d" unit to be recognized when creating a bucket since it's typical to create RP in days, like 7d, 30d etc.

__Alternatives considered:__
Convert days to hours and use 'h' unit instead.

__Use case:__
Since most people create RPs in terms of days, this would eliminate having to convert to hours and be less confusing.

### PR DESCRIPTION
**Pull request by jsteenb2**
Closes #18639 

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

**Comment by sanderson** [comment]
@kelsiev FYI 👆

**Comment by jsteenb2** [comment]
@sanderson / @kelseiv I decided to just get days in for now. I am not sure how to integrate the months/years into this with all the special cases involved (short months (feb), leap year, yada yada). WIll need to follow up, if product wants it, to support the month/year duration.

**Comment by kelseiv** [comment]
Thank you, @sanderson @jsteenb2. That was quick! Makes sense. Day seems most important per the reasons in @abalone23 's request. It sounds like week is next in importance given we supported that in 1.x. 
Although years and months are more complex to implement, it seems to make sense to eventually support retention policies using any Flux duration literal, as you suggested Johnny.

**Comment by jsteenb2** [comment]
I forgot about the `week` duration. I put up a PR to add that, is a trivial extension to the existing.

https://github.com/influxdata/influxdb/pull/18659

**Comment by jsteenb2** [comment]
we're good now, week is merged :-)

**Pull request merged**
