### PR TITLE
Configurable precision on UDP services

### PR DESCRIPTION
**Pull request by tpitale**
* pass configured precision string to point parsing
* add Precision configuration to UDP config
* default configured precision to match what it appears to be now (from ParsePoints)

### CODE REVIEW

**Comment by tpitale** [comment]
Potentially resolves #5564

**Comment by jwilder** [comment]
@tpitale Can you update the changelog as well?  :+1:  after that.

**Comment by tpitale** [comment]
@jwilder how's that look?

**Comment by jwilder** [comment]
Thanks @tpitale!

**Comment by kols** [comment]
release note states this is in version v0.10.0 but instead I see this pr only included from v0.11.0.
and i upgraded influxdb for the feature only to find it's not there. a mistake?

**Comment by tpitale** [comment]
Probably a mistake. Appears I added it to the last section of the changelog, but it got merged as part of the 0.11.0 milestone.

**Pull request merged**
