### PR TITLE
Parallelize compression/decompression during backup and restore

### PR DESCRIPTION
**Pull request by pliu**
Drop-in of pgzip for gzip

Compression for the backup and restore commands of influxd were able to download the data from the database quickly, but subsequent compression and decompression was done in a single-threaded manner that is extremely slow.

###### Required for all non-trivial PRs
- [ x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by e-dard** [comment]
@pliu thanks for the contribution. Whilst the code changes in this PR are trivial, there may be significant changes to the behaviour of the database. In order to accept this contribution it would be good to see some benchmarks or performance tests.

Further, the core team would probably need to look into the third part library and check it's suitable for inclusion. /cc @aanthony1243

**Comment by aanthony1243** [comment]
agreed, once we update for dep, this is ok to merge.

**Comment by pliu** [comment]
@e-dard Feel free to make the necessary changes :) Thank you!

**Comment by e-dard** [comment]
@pliu hi, can you cherry pick this commit into your branch? https://github.com/influxdata/influxdb/commit/4712404b1ead81764be5dd03affd589b1bd144f1

**Comment by pliu** [comment]
@e-dard Done

**Pull request merged**
