### PR TITLE
refactor: remove lower lock in last cache

### PR DESCRIPTION
**Pull request by hiltontj**
Part of #25095

This contains a single commit, and changes the `LastCache` design to eliminate the lower lock that was introduced in #25143.

I will leave a review with comments/concerns in-line.

### CODE REVIEW

**Review by hiltontj — COMMENTED** [review]
In general I think this simplifies the implementation but I'm concerned of the possibility for a race condition, i.e., between the time that the `TableProviderImpl::call` function is called, which now produces a `LastCacheFunctionProvider`, and when the `TableProvider::scan` (or `TableProvider::schema`) method(s) are called on that type.

If a cache is modified/removed between those calls, which in theory is possible because they use separate locks, then there will be a discrepancy in the state of the cache, which could lead to undefined behaviour or panics.

@pauldix 

---

As an aside, one of the things I looked into before, when I was grappling with lifetimes, was the use of forwarding the `RwLock` guard using, e.g., [`MappedRwLockReadGuard`](https://docs.rs/parking_lot/0.12.3/parking_lot/type.MappedRwLockReadGuard.html). This would be to forward the lock acquired by `TableFunctionImpl::call` to the `TableProvider`, but this still fell apart with the borrow checker because the mapped guard has a lifetime that is not `'static`.

**Comment by pauldix** [comment]
@hiltontj I think you can manage the race conditions. If the cache is removed, then you should be able to check for that and just return an empty record batch? If it's modified, that seems fine to me as you're just returning the most up to date view of the data.

**Comment by hiltontj** [comment]
> If the cache is removed, then you should be able to check for that and just return an empty record batch?

That definitely sounds reasonable.

> If it's modified, that seems fine to me as you're just returning the most up to date view of the data.

This one I had to think a bit more about, but I am pretty sure that it will not be an issue. I was worried of a scenario like so:

* At t<sub>0</sub> the `TableProvider::schema` is used to determine a projection
* At t<sub>1</sub> the data is modified
* At t<sub>2</sub> the projection from t<sub>0</sub> is passed to `TableProvider::scan`.

However, for the case where fields are added, then a projection which is based on the schema from t<sub>0</sub> will still be valid for the data in the modified state at t<sub>2</sub> (because new fields are always appended to the cache schema).

Given that, I will clean this up and cherry pick the commits into the target branch.

**Comment by hiltontj** [comment]
Closing as the commit was cherry-picked onto https://github.com/influxdata/influxdb/pull/25143 (https://github.com/influxdata/influxdb/pull/25143/commits/f9210e94347024a985242ca66d02e20c04b785c3)

**Pull request closed without merging**
