### PR TITLE
Limit concurrent shards loading to number of cores available

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass

### CODE REVIEW

**Comment by jwilder** [comment]
@corylanou Forgot to push this up w/ #6623

**Comment by joelegasse** [comment]
It might be uncommon, but this should probably be limited to the minimum of `NumCPU` and `GOMAXPROCS`. If someone has multiple cores, but manually sets `GOMAXPROCS=1`, then we'll have concurrent goroutines that will be fighting for a single active OS thread.

**Comment by jwilder** [comment]
Maybe `runtime.GOMAXPROCS(0)` then?  Should default to `NumCPU` unless changed.

**Comment by joelegasse** [comment]
For Go 1.5+, yes, just checking the value of `GOMAXPROCS` should work.

**Comment by joelegasse** [comment]
LGTM 👍

**Pull request merged**
