### PR TITLE
Return the time with a selector when there is no group by interval

### LINKED ISSUE #5890: [0.11] FIRST(),LAST() no longer return the relevant timestamp and values seem off
Using the [sample data](https://docs.influxdata.com/influxdb/v0.10/sample_data/data_download/) from the docs:
* `first()` and `last()` no longer return the relevant timestamp in 0.11
* `first()` and `last()` don't return the same point in 0.10 and 0.11

**0.10**
```
> SELECT FIRST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			        first
2015-08-18T00:00:00Z	2.064
> SELECT LAST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			         last
2015-09-18T21:42:00Z	 4.938
```

**0.11**
```
> SELECT FIRST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			        first
1970-01-01T00:00:00Z	5.597
> SELECT LAST(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			        last
1970-01-01T00:00:00Z	5.745
```

I believe 0.10 has the right answer:
```
#First values of water_level

> SELECT water_level FROM h2o_feet WHERE location = 'santa_monica' LIMIT 3
name: h2o_feet
--------------
time			        water_level
2015-08-18T00:00:00Z	2.064
2015-08-18T00:06:00Z	2.116
2015-08-18T00:12:00Z	2.028

# Last values of water_level

> SELECT water_level FROM h2o_feet WHERE location = 'santa_monica' ORDER BY time DESC LIMIT 3
name: h2o_feet
--------------
time			        water_level
2015-09-18T21:42:00Z	4.938
2015-09-18T21:36:00Z	5.066
2015-09-18T21:30:00Z	5.01
```

I've tried to reproduce the 'getting the wrong point' issue in another data set and I can't!

### PR DESCRIPTION
**Pull request by jsternberg**
The time of the point will be returned with a selector when there is no
group by interval and when there is only one selector. Any other
conditions will return the start time of the interval.

Fixes #5890.

### CODE REVIEW

**Comment by e-dard** [comment]
LGTM 👍

**Comment by beckettsean** [comment]
@jsternberg I think this works for MAX, MIN, and PERCENTILE as well, but the tests only reference FIRST and LAST. Can you clarify?

**Comment by jsternberg** [comment]
I think that there weren't any tests with MAX, MIN, or PERCENTILE that didn't use a group by interval and that's the only way this change shows up. It should work with all of those.

**Comment by beckettsean** [comment]
Cool, thanks. 

@jsternberg if I have more than one selector function but no `GROUP BY`, do the selectors simply return `0` as the timestamp?

E.g.  With `SELECT FIRST(value), LAST(value) FROM foo` I'd get epoch 0 as the timestamp for both, but with `SELECT FIRST(value) FROM foo; SELECT LAST(value) FROM foo;` I'd get the actual timestamp for both.

**Comment by jsternberg** [comment]
Yes, you are correct. It would do exactly that except it would return the time of whatever the start time is (not necessarily the epoch if you have restricted the time period).

**Comment by beckettsean** [comment]
Okay, I see, thanks. So `SELECT FIRST(value), LAST(value) FROM foo` would give me 0 as the timestamp but `SELECT FIRST(value), LAST(value) FROM foo WHERE time > now() - 10m` would give me exactly 10 minutes ago as the timestamp?

**Comment by jsternberg** [comment]
Yep. 👍 

That's the same behavior for all of the other aggregates too.

**Pull request merged**
