### PR TITLE
edit InfluxDB license info so that GitHub recognizes it

### PR DESCRIPTION
**Pull request by eirinikos**
Hello! 👋

(CCing @dankohn who has requested this work so that the license will appear correctly in https://landscape.cncf.io/selected=influx-db)

GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.

This commit renames LICENSE_OF_DEPENDENCIES.md to DEPENDENCIES.md, which
allows Licensee to ignore the file when checking the repository's
license type. It also adds a "Licensing" section to the README so that
users will understand the intent of the DEPENDENCIES.md file.

Collectively, these changes allow Licensee to successfully identify the
license type of InfluxDB's codebase as MIT.

I also updated the license info for Opentracing-Go, which is now
Apache-licensed and no longer MIT-licensed.

###### Required for all non-trivial PRs
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by e-dard** [comment]
@eirinikos this LGTM. I just need to check with a couple of folks if we have any hard links anywhere (internally or otherwise) to `LICENSE_OF_DEPENDENCIES`.

**Comment by eirinikos** [comment]
@e-dard Makes sense, thanks for the note!

**Comment by jsternberg** [comment]
@eirinikos is the current revision that we use for opentracing licensed under the Apache license? Can you also point me to the documentation for the `DEPENDENCIES.md` file? I can't seem to find it in the Licensee gem documentation.

**Comment by eirinikos** [comment]
@jsternberg Good questions. If I understand correctly, then your `Godeps` file currently references an [opentracing commit](https://github.com/opentracing/opentracing-go/commit/328fceb7548c744337cd010914152b74eaf4c4ab) that precedes [the commit that's responsible for the license switch](https://github.com/opentracing/opentracing-go/commit/5a4c9c6b841c283274c4b55324f9da7257d8c211) by 2 commits. Is this a problem?

And you're right, Licensee documentation doesn't mention any naming convention in regards to a specific `DEPENDENCIES.md` file. AFAIK, there is no universal standard for how an open-source software project is supposed to document the licensing for all of its dependencies. It was my own decision to rename the file from `LICENSE_OF_DEPENDENCIES` to `DEPENDENCIES`.

It was necessary to remove the word `LICENSE` from the dependencies list filename; otherwise Licensee would try and fail to parse `LICENSE_OF_DEPENDENCIES.md` as a license file in itself.

To illustrate the point, below is the output that I get from running the `licensee` command-line tool on the InfluxDB repo. As you can see, Licensee reads `LICENSE_OF_DEPENDENCIES.md` as a license file and is unable to match the file's contents against an existing open-source license. If Licensee detects more than `Matched file` (as it does in this situation), and if it does not detect the same license type for all `Matched files`, then it will report `Other` as the license type for the entire repository.

I hope this all makes sense! 

```
$ licensee detect https://github.com/influxdata/influxdb
License:        Other
Matched files:  LICENSE, LICENSE_OF_DEPENDENCIES.md
LICENSE:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright (c) 2013-2016 Errplane Inc.
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT License
LICENSE_OF_DEPENDENCIES.md:
  Content hash:  165f89148da3e2f2e06076acf806f1695794b3e3
  License:       Other
  Closest licenses:
    OFL-1.1 similarity:   4.52%
    WTFPL similarity:     4.35%
    LGPL-3.0 similarity:  3.99%
```

**Comment by timhallinflux** [comment]
@stevebang review links from docs and potential impact of this change.

**Comment by gshif** [comment]
I have run the following commands (ass suggested by the link above to resolve conflicts):
- git checkout -b eirinikos-update-license master
- git pull https://github.com/eirinikos/influxdb.git update-license
- git push
- The build results could be found here : https://ci.influxdb.com/job/influxdb/job/eirinikos-update-license/
- The doc changes are tracked here : https://github.com/influxdata/docs.influxdata.com/issues/1858

**Pull request merged**
