### PR TITLE
[0.10.2] Backport #5716 to 0.10.0

### PR DESCRIPTION
**Pull request by jonseymour**
This PR makes the #5716 fix available in 0.10.x.

These commits are actually the same commits that have already been merged into master - this PR will simply merge these commits into 0.10.0 and aim to eliminate a panic that occurs in the 0.10.x builds.

- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by zstyblik** [comment]
@jonseymour, but v0.10.2 has already been released.

**Comment by jonseymour** [comment]
@zstyblik sorry I interpreted [0.10.2] as being a statement about which version had the issue, rather than which version the fix will be delivered in. I have adjusted the title accordingly.

**Comment by zstyblik** [comment]
@jonseymour, I see and you're right. I got confused by backport stuff V. the usual ``vX.Y has such and such issue``. My bad. Now, I'm even more confused, because this means life ov v0.10 will be prolonged even more which is a bit unexpected. In other words, my expectation was v0.10.2 was the last one before v0.11 is here.

**Comment by jonseymour** [comment]
@zstyblik The existence of this PR does not mean there will be a 0.10.3 - that's a call for inlfuxdata to  make, not me. 

This PR contains a fix that could be trivially included in a hypothetical 0.10.3 if influxdata decides to build one. I opened the PR so that the fix is easily at hand, should they choose to use it.

**Comment by jwilder** [comment]
@jonseymour Could you rebase?

**Comment by jonseymour** [comment]
@jwilder conflict resolved in #5911 now.

**Comment by jonseymour** [comment]
Repushed to deal with (spurious?) CI test failure.

**Pull request merged**
