### PR TITLE
Support tools for running async queries

### LINKED ISSUE #6992: [Feature Request] Batch create databases
### Feature Request

__Proposal:__  Batch mode for CREATE DATABASE

__Current behavior:__  There is no current batch processing for creating a database, thus creating even 100 databases takes several seconds as each query is posted and processed. 

__Desired behavior:__ The ability to batch create new databases. For example, a text file containing a list of database names separated line-by-line.
```
curl -XPOST 'localhost:8086/query/create' --data-binary @dbnames.txt
```

__Use case:__ For some data models where data cannot be stored in a single database due to it having sensitive information and should only be accessible by the allowed users, thus requiring separate username/password for each database. Therefore, importing data would also require the creation of many databases which currently takes several minutes, high cpu and a large amount of memory to create 10,000 databases.

### PR DESCRIPTION
**Pull request by jsternberg**
Fixes #6992.

### CODE REVIEW

**Comment by gunnaraasen** [comment]
I think returning the result to the client along with any errors would be helpful. Otherwise it'll be hard to tell when the batch has finished running.

**Comment by jsternberg** [comment]
We can't really return any errors since, by definition, batch means that the HTTP client isn't going to stick around to see if there was any error. The best we can do is just log them. Anything else and we would have to maintain a record of the result status until someone checked it and we don't really want to do the job of a full job server, especially since it can result in people forgetting to ack the results and lead to zombie batch processes.

**Comment by corylanou** [comment]
I think the concept is sound.  I don't know if I like the term `batch` as you can do batch already with the `;` syntax.  This is more about `asynchronous` than it is batch imo.  Thoughts?

**Comment by jsternberg** [comment]
Hm, I was always under the impression that's what batch meant. Batch processing systems are usually commands you insert and then get run asynchronously by the system at its convenience. In contrast, an interactive session would be something that returned the output as it was produced and is connected to an HTTP connection.

Am I wrong? We can change it to `async` pretty easily.

**Comment by jsternberg** [comment]
After an offline conversation, I changed `batch` to `async` since it sounds better and describes exactly what this does.

**Comment by corylanou** [comment]
👍

**Comment by gunnaraasen** [comment]
I like `async` much better. 👍

**Comment by rkuchan** [comment]
@jsternberg, is the syntax to do this like the syntax shown in the original issue:
```
curl -XPOST 'localhost:8086/query/create' --data-binary @dbnames.txt
```
Where dbnames.txt would have a list of queries separated by a newline?

**Comment by jsternberg** [comment]
Nope. It wasn't possible to do the query that way. Instead, we do it by attaching a file using multipart POST. To do that with `curl`, you can do this:

```
curl -F "q=@database.iql" -F "async=true" http://localhost:8086/query
```

**Pull request merged**
