### PR TITLE
fix(models): Remove tsdb package dependency from tests

### PR DESCRIPTION
**Pull request by stormasm**
Closes #

Describe your proposed changes here.

Discussed with Jonathan Sternberg today on Slack...
Feb 18, 2020

https://influxcommunity.slack.com/archives/CH8RV8PK5/p1582066416080000?thread_ts=1582064001.068600&cid=CH8RV8PK5

One very simple change on points_test.go re-enables having model
be stand alone and not need any other influxdb packages which
is very helpful and handy for many reasons...

### CODE REVIEW

**Comment by stormasm** [comment]
https://github.com/stormasm/influx-models/blob/master/influxdb/go.mod

You can see here now that the models package has no dependencies...
Which is the idea behind this pull request...

**Comment by stormasm** [comment]
@jsternberg 
@stuartcarnie finished his review...
Is there anything else I need to do on my end for the merge to happen ?
Thanks kindly for your input.
Michael

**Comment by jsternberg** [comment]
@stormasm can you amend the commit itself to update the commit message to the proper format? Also make sure that you have signed the [CLA](https://influxdata.com/community/cla/). I'll merge it when the commit message is updated and you have confirmed that you have signed the CLA.

**Comment by stormasm** [comment]
@jsternberg 
I signed the CLA and updated the commit message...
thanks for your patience and helping me out...

**Pull request merged**
