### PR TITLE
Add support for "syslog" logging

### PR DESCRIPTION
**Pull request by malthe**
Supports `file` configuration with values `syslog`, `local0`, ..., `local7`.

This closes https://github.com/influxdb/influxdb/issues/896.

### CODE REVIEW

**Comment by kbabioch** [comment]
What's the current status on this? It seems that it is no longer possible to log using syslog. Code-wise a lot has changed since this commit and I cannot find any references to syslog within the current code base. The whole configuration section is gone by now. Is this a regression?

**Comment by swdream** [comment]
@kbabioch it is removed here
https://github.com/influxdata/influxdb/commit/06bfd9c496becacff404e6768e7c0fd8ce9603c2
I also am finding a way to push log into syslog, but cannot find out :(

**Comment by kbabioch** [comment]
@swdream I've opened up another feature request (#7190). Hopefully it will get some more attention there, since this one is already merged, so maybe nobody is taking notice here.

**Comment by swdream** [comment]
@kbabioch ok, thanks

**Pull request merged**
