### PR TITLE
removed condition check to check if values are returned for queries so that the admin ui displays the same results as cli

### PR DESCRIPTION
**Pull request by Vidhuran**
Fixes Issue #4688

### CODE REVIEW

**Comment by jwilder** [comment]
Verified this fixes `show continuous queries` in the admin UI.  @toddboom change look ok?

@Vidhuran Can you sign the CLA? https://influxdata.com/community/cla/

**Comment by Vidhuran** [comment]
@jwilder : Done

**Comment by Vidhuran** [comment]
- [✓] CHANGELOG.md updated
- [✓] Rebased/mergable
- [✓] Tests pass
- [✓] Sign [CLA](https://influxdata.com/community/cla/)

**Comment by jwilder** [comment]
@Vidhuran can you rebase?

**Comment by Vidhuran** [comment]
@jwilder : Done , I've now rebased to the latest master

**Comment by jwilder** [comment]
Thanks @Vidhuran!

**Pull request merged**
