### PR TITLE
Update the required fields for task swagger

### LINKED ISSUE #12276: task: creation response is missing required key which is not part of the schema
I created a task from the command line:

```
./bin/darwin//influx task create --org a 'option task = {name: "x", every: 2m} from(bucket:"a") |> range(start:-1m) |> to(bucket: "c", org: "a")'
ID			Name	OrganizationID		Organization	AuthorizationID		Status	Every	Cron
03799abd11158000	x	0379950a5aee3000	a		0379950a5aee3002	active	2m0s
```

The validator branch pointed out that the response is missing the required `organization` key, but only `org` and `orgID` are valid keys according to the schema:

```
SWAGGER RESPONSE VALIDATION ERROR: Property 'organization' is missing
Schema:
  {
    "properties": {
      "authorizationID": {
        "description": "The ID of the authorization used when this task communicates with the query engine.",
        "type": "string"
      },
      "createdAt": {
        "format": "date-time",
        "readOnly": true,
        "type": "string"
      },
      "cron": {
        "description": "A task repetition schedule in the form '* * * * * *'; parsed from Flux.",
        "type": "string"
      },
      "every": {
        "description": "A simple task repetition schedule; parsed from Flux.",
        "type": "string"
      },
      "flux": {
        "description": "The Flux script to run for this task.",
        "type": "string"
      },
      "id": {
        "readOnly": true,
        "type": "string"
      },
      "labels": {
        "$ref": "#/components/schemas/Labels"
      },
      "latestCompleted": {
        "description": "Timestamp of latest scheduled, completed run, RFC3339.",
        "format": "date-time",
        "readOnly": true,
        "type": "string"
      },
      "links": {
        "example": {
          "logs": "/api/v2/tasks/1/logs",
          "members": "/api/v2/tasks/1/members",
          "owners": "/api/v2/tasks/1/owners",
          "runs": "/api/v2/tasks/1/runs",
          "self": "/api/v2/tasks/1"
        },
        "properties": {
          "logs": {
            "format": "uri",
            "type": "string"
          },
          "members": {
            "format": "uri",
            "type": "string"
          },
          "owners": {
            "format": "uri",
            "type": "string"
          },
          "runs": {
            "format": "uri",
            "type": "string"
          },
          "self": {
            "format": "uri",
            "type": "string"
          }
        },
        "readOnly": true,
        "type": "object"
      },
      "name": {
        "description": "A description of the task.",
        "type": "string"
      },
      "offset": {
        "description": "Duration to delay after the schedule, before executing the task; parsed from flux.",
        "type": "string"
      },
      "org": {
        "description": "The organization that owns this Task.",
        "type": "string"
      },
      "orgID": {
        "description": "The ID of the organization that owns this Task.",
        "type": "string"
      },
      "status": {
        "default": "active",
        "description": "The current status of the task. When updated to 'inactive', cancels all queued jobs of this task.",
        "enum": [
          "active",
          "inactive"
        ],
        "type": "string"
      },
      "updatedAt": {
        "format": "date-time",
        "readOnly": true,
        "type": "string"
      }
    },
    "required": [
      "name",
      "organization",
      "flux"
    ],
    "type": "object"
  }

Value:
  {
    "authorizationID": "0379950a5aee3002",
    "every": "2m0s",
    "flux": "option task = {name: \"x\", every: 2m} from(bucket:\"a\") |\u003e range(start:-1m) |\u003e to(bucket: \"c\", org: \"a\")",
    "id": "03799abd11158000",
    "labels": [],
    "links": {
      "labels": "/api/v2/tasks/03799abd11158000/labels",
      "logs": "/api/v2/tasks/03799abd11158000/logs",
      "members": "/api/v2/tasks/03799abd11158000/members",
      "owners": "/api/v2/tasks/03799abd11158000/owners",
      "runs": "/api/v2/tasks/03799abd11158000/runs",
      "self": "/api/v2/tasks/03799abd11158000"
    },
    "name": "x",
    "org": "a",
    "orgID": "0379950a5aee3000",
    "status": "active"
  }

```

### PR DESCRIPTION
**Pull request by lyondhill**
Closes #12276

### CODE REVIEW

**Comment by lyondhill** [comment]
@mark-rushakoff I believe we have several other fields that are always present. I am not sure if we want to make them "required" or not. 
If we want to require a larger list of fields we could start with the group of fields that are not omitted when empty.

```
	OrganizationID  ID     `json:"orgID"`
	Organization    string `json:"org"`
	AuthorizationID ID     `json:"authorizationID"`
	Name            string `json:"name"`
	Status          string `json:"status"`
	Flux            string `json:"flux"`
```
What do you think?

**Comment by lyondhill** [comment]
The current swagger.yml requires "organization" on a task. but the task only has "orgID" and "org". When we changed organization which used to represent the org id we forgot to update the required section of swagger's task definition.

**Comment by mark-rushakoff** [comment]
I'm pretty sure at this point that the Task value is only returned from the server, i.e. it is read-only from the API consumer's perspective. The TaskCreate and TaskUpdate values are used for POST and PATCH. If that's accurate, then setting them Required just indicates to the client that they can rely on those fields being present.

Maybe @influxdata/api can help clarify which is more appropriate here.

**Comment by lyondhill** [comment]
I think that is true mark. I think we should definitely make ID required.

**Pull request merged**
