### PR TITLE
Performance optimization suggestions

### PR DESCRIPTION
**Pull request by huhue**
In my test, this optimization can improve performance 20%.  This optimization can make full use of my machine's CPU.
The big reason is that my test machine performance is better, 64-core cpu, ssd disk.
This optimization is what I found out through the flame graph, but sorry for the flame graph is lost.

I use influxdb own stress tools. stress config like this:
```
[provision]
  [provision.basic]
    enabled = true
    address = "xxxx:xxxx"
    database = "xxxx"
    reset_database = false

[write]
  [write.point_generator]
    [write.point_generator.basic]
      point_count = 1000
      series_count = 1000000
      tick = "10s"
      jitter = true
      precision = "s"
      measurement = "cpu"
      start_date = "2009-Jan-02"
      [[write.point_generator.basic.tag]]
        key = "host"
        value = "server"
      [[write.point_generator.basic.tag]]
        key = "location"
        value = "us-west"
      [[write.point_generator.basic.field]]
        key = "value"
        value = "float64" # supported types: float64, int, bool
      [[write.point_generator.basic.field]]
        key = "test_filed_int"
        value = "int" # supported types: float64, int, bool
      [[write.point_generator.basic.field]]
        key = "test_filed_bool"
        value = "bool" # supported types: float64, int, bool

  [write.influx_client]
    [write.influx_client.basic]
      enabled = true
      addresses = ["xxxx:xxxx"] 
      database = "stress"
      precision = "s"
      batch_size = 10000
      batch_interval = "0s"
      concurrency = 100
      ssl = false
      format = "line_http" 
      retention-policy = "xxxx"
```

### CODE REVIEW

**Comment by stuartcarnie** [comment]
@huhue thanks for the PR; looks good to me 🎉

**Comment by stuartcarnie** [comment]
@huhue we had to revert the change as we require a signed CLA, which you can do here •  https://www.influxdata.com/legal/cla/

**Comment by huhue** [comment]
I already signed CLA. 
sorry for my first commit for influxdb.

**Comment by rbetts** [comment]
Hi @huhue. Did you sign the CLA using this github account / name? I need to
verify against our bookkeeping. If you'd prefer, you can email me directly
at ryan@influxdata.com.

**Comment by huhue** [comment]
I complete signed CLA in address https://www.influxdata.com/legal/cla/ 
please check in the bookkeeping.

**Comment by timhallinflux** [comment]
Confirmed CLA signed as of: 5/23/2018 2:49:36Z

**Pull request merged**
