### PR TITLE
Add notes on how to avoid downtime when upgrading

### PR DESCRIPTION
**Pull request by mjdesa**

### CODE REVIEW

**Comment by mjdesa** [comment]
@beckettsean

**Comment by beckettsean** [comment]
:+1:

**Comment by jwilder** [comment]
@mjdesa Can you rebase.  :+1:  otherwise.

**Comment by beckettsean** [comment]
@mjdesa I updated the wording in https://github.com/influxdata/docs.influxdata.com/pull/212/files#r52399685, I suggest updating this to reflect those changes.

**Comment by mjdesa** [comment]
Opening https://github.com/influxdata/influxdb/pull/5620 in favor of rebasing.

**Pull request closed without merging**
