### PR TITLE
tsm: ensure that snapshot writes are eventually retried/released, even if WriteSnapshot fails

### PR DESCRIPTION
**Pull request by jonseymour**
This is my attempt to fix the code review issue I identified in #5686.

The controversial aspect of this fix may be the introduction of a commit lock that ensures that
at most one thread is writing a snapshot for a given shard at a given time. I think the lock 
is justified because reasoning about concurrent execution of these code paths seems fraught with
danger. Of course, if there are contrary opinions, lets discuss.

### CODE REVIEW

**Comment by jonseymour** [comment]
Oops. I need to re-roll with corresponding changes to the test.

**Comment by jonseymour** [comment]
Actually, thinking about this some more, I realise that the concurrent write of multiple snapshots is an essential and intended part of the design. So, I'll will withdraw this PR for now until I have a chance to make rollback work in the presence of such concurrency.

**Comment by jonseymour** [comment]
On reflection, I think this fix is probably incomplete, since I don't think the write for the latest snapshot will do what is required to gather the keys from snapshots that failed to be written on a previous WriteSnapshot() call so we end up losing that data from those snapshots. I need to think about this some more, I think. Will re-open the PR when/if I find a solution.

**Comment by jonseymour** [comment]
Previously, if a snapshot write failed, the memory was never released **and** the associated writes were never retried. 

Furthermore, if the write error was transient and a subsequent compact was successful, then associated WAL segments would be deleted without ever having been written into TSM files. Such a data loss would not be apparent until influxd was restarted (because the data would still be served from the cache).

Interestingly, these issues made influxd less resilient in the face of transient write errors that apparently do not require a server restart, than in the presence of permanent write errors that do. The reason is that provided the WAL segments are not deleted, the normal influxd restart process will eventually compact the WAL segments associated with failed snapshot writes. However, if the write errors are only transient, then the next successful compaction will delete the WAL segments without them ever having been written to disk. 

This series should address these issues.

**Comment by jonseymour** [comment]
I have now added some tests for the rollback functionality. The new and revised tests show how the association between a cache snapshot and a slice of WAL segment names is established and how WriteSnapshots() can use this capability to retry previously failed snapshot writes.

**Comment by jonseymour** [comment]
Fixed a potential thread safety issue - PrepareSnapshots() now returns a clone of the snapshots slice, rather than a reference. This allows the snapshotter to modify the contents of the slice without interfering with queries that may be trying to use it.

**Comment by jonseymour** [comment]
**note: **Commits prior to 7059331 are from PR #5778 and will not be delivered by the final version of this PR

**Comment by jonseymour** [comment]
This query output shows how this fix recovered the snapshots that could not be written because of temporary removal of write permission to the shard's TSM directory. When the write permissions were restored, the snapshot count dropped to zero again.

demonstration of fix

**Comment by jonseymour** [comment]
@jwilder - example of a (manual) integration test output which shows that this fix does what it intends to do.

**Comment by jonseymour** [comment]
Rebased to remove "comment only assertions" commit that was removed from another PR.

**Comment by jwilder** [comment]
@jonseymour I think supporting the multiple snapshots in the cache is not necessary and is complicating things.  I have an alternative fix in #5789 that removes the multiple snapshot support.

**Comment by jonseymour** [comment]
Rebased onto a merge of #5701 and 2894234b.

**Comment by jwilder** [comment]
@jonseymour I'm closing this in favor of #5789 because it resolves #5686 by removing some unnecessary complexity in the cache.  Since we don't need the multiple snapshots, it does not make sense to add additional layers on top of them that adds additional complexity to the cache.

**Pull request closed without merging**
