### PR TITLE
fix(build): building arm 6

### PR DESCRIPTION
**Pull request by gshif**
Please see https://github.com/influxdata/influxdb/issues/19755 for more details.

Closes # https://github.com/influxdata/influxdb/issues/19755

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Feature flagged (if modified API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Review by stuartcarnie — COMMENTED** [review]
@gshif does this change the output of the JSON in any way?

**Comment by gshif** [comment]
@stuartcarnie to be honest I do not know, but all of the unit and litmus integration tests passed. Is there a simple way to check?

**Comment by docmerlin** [comment]
It shouldn't change the json output.  Marshaling a time.Duration to json outputs a number type, as does using a uint.

**Review by stuartcarnie — APPROVED** [review]
Ok, given the serialized format doesn't change, looks good to me 👍

**Pull request merged**
