### PR TITLE
[tsm1] Change timestamp from time.Time to unixnano

### PR DESCRIPTION
**Pull request by methane**
time.Time contains timezone `loc *Location`.
Since tsm1.Cache holds a lot of values in heap, there are many pointers in heap.
This makes GC heavy.

```
before:
$ go test -run=xxx -bench=BenchmarkCache
PASS
BenchmarkCacheFloatEntries-4         300       4019495 ns/op

after:
$ go test -run=xxx -bench=BenchmarkCache
PASS
BenchmarkCacheFloatEntries-4         500       3720449 ns/op
```

related issues:
* golang/go#14189
* #5217 

---

- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

### CODE REVIEW

**Comment by jwilder** [comment]
Thanks @methane.  I see similar improvements locally.  There are other places where `time.Time` is used and a change like this might help them as well.

```
influxdb:influxdb jason$ go test -run non -bench BenchmarkCacheFloatEntries -benchmem ./tsdb/engine/tsm1/
PASS
BenchmarkCacheFloatEntries	     500	   3368979 ns/op	  593239 B/op	   30016 allocs/op
```

```
influxdb:influxdb jason$ go test -run non -bench BenchmarkCacheFloatEntries -benchmem ./tsdb/engine/tsm1/
PASS
BenchmarkCacheFloatEntries	     500	   3120040 ns/op	  433206 B/op	   30015 allocs/op
```

**Comment by methane** [comment]
I've seen profiler output posted on golang/go#14189.
I found most of memory is consumed by this cache.
So this is the largest part of memory consumption and GC time.

**Comment by e-dard** [comment]
LGTM :+1:

**Comment by methane** [comment]
@toddboom Would you run the benchmark same to golang/go#14189  ?

**Pull request merged**
