### PR TITLE
feat(clientLibs): add Swift library to UI

### PR DESCRIPTION
**Pull request by bednar**
1. add Swift client library

The `swiftLogo.svg` is a placeholder for real logo.

Screenshot 2021-01-28 at 11 53 43

Screenshot 2021-01-28 at 11 54 07

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by russorat** [comment]
preview of the updated swift logo

image

**Review by danxmoran — COMMENTED** [review]
The change looks good, @bednar can you add a line to `CHANGELOG.md`?

**Comment by russorat** [comment]
@danxmoran added changelog

**Review by danxmoran — APPROVED** [review]
I'll turn the knobs on my end to make CI happy, thanks!

**Pull request merged**
