### PR TITLE
Various fixes for binary expression math between iterators

### LINKED ISSUE #5973: [0.11.0] Match points between two iterators for binary math
Binary math is currently done by just reading each iterator and adding the next point from each one to the other. This kind of approach worked for one iterator against a literal because the literal never changed, but it doesn't work for two iterators because they could return different points from each other and become out of sync very easily.

Fix the binary math between two iterators to match the two sides with each other and handle skipped or mismatched points.

Related to #5959.

### PR DESCRIPTION
**Pull request by jsternberg**
Closes #5973.

### CODE REVIEW

**Comment by jwilder** [comment]
LGTM but @benbjohnson should probably take a look too.

**Comment by benbjohnson** [comment]
@jsternberg What about validating call+ref combinations in calls? e.g.

```
SELECT count(foo + sum(bar)) ...
```

It seems like you should nest the validation inside the `Call` for its `Expr`.

**Comment by jsternberg** [comment]
@benbjohnson that combination is forbidden by another validation right before it since math isn't allowed inside of a call. I've added that as a test case so that when the math restriction is removed by #5971 we won't forget about validating this as an error.

**Comment by jsternberg** [comment]
I made a modification to the validation so both the `top()`/`bottom()` validation and the mixed aggregate and raw field validation are recursive and added some more test cases.

**Comment by benbjohnson** [comment]
:+1:

**Pull request merged**
