### PR TITLE
Rename influxdb/influxdb to influxdata/influxdb

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This pull request changes all the import and URL references from:

    github.com/influxdb/influxdb

to:

    github.com/influxdata/influxdb

### CODE REVIEW

**Comment by jsternberg** [comment]
:+1:

**Comment by jwilder** [comment]
What changes happened to `CHANGELOG.md`?

**Comment by benbjohnson** [comment]
It changed the URLs to issues & pull requests in CHANGELOG.

**Comment by jwilder** [comment]
Ah. :+1:

**Comment by benbjohnson** [comment]
Added canonical paths: d9a6a73

**Comment by jwilder** [comment]
:+1:

**Pull request merged**
