### PR TITLE
chore: Sync and release v1.0.1 of influxdb-line-protocol

### PR DESCRIPTION
**Pull request by powersj**
* Increase influxdb-line-protocol version
* run `cargo rdme`
* Pull changes from influxdb_iox
  * only missing: https://github.com/influxdata/influxdb_iox/commit/61082a000005cd2f88cfd3799072e3e14e3d5005

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @powersj 

I think I missed the code change in this PR (I see only a new test). 

Or are you saying that a change that hasn't been released is commited into this repo, and all that remains is to publish a new version of this crate?

**Comment by powersj** [comment]
> Or are you saying that a change that hasn't been released is commited into this repo, and all that remains is to publish a new version of this crate?

Correct the code changes are already here and it looks like we only need a release.

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
I reviewed the changes since 28cb56767c76c5b670a70bb695c2141a64865b88 when I belive this crate was last released, and I think there are breaking API changes -- for example new `Error` enums like `TagSetMalformed` that came in from https://github.com/influxdata/influxdb/commit/8afa2f47

Thus I am going to bump the version number on this PR to be safe to `2.0.0`

**Comment by alamb** [comment]
Ok, I have published version 2.0 to crates.io: https://crates.io/crates/influxdb-line-protocol/2.0.0

**Pull request merged**
