### PR TITLE
Show disk usage reduction factor post-compression

### PR DESCRIPTION
**Pull request by otoolep**
```
Summary statistics
========================================
Databases converted:                 1
Shards converted:                    9
TSM files created:                   9
Points read:                         5488922
Points written:                      5488922
NaN filtered:                        0
Inf filtered:                        0
Points without fields filtered:      0
Disk usage pre-conversion (bytes):   252182528
Disk usage post-conversion (bytes):  4808331
Reduction factor:                    99%
Total conversion time:               8.058645003s
```

### CODE REVIEW

**Comment by otoolep** [comment]
@jwilder

**Comment by jwilder** [comment]
Can you add a bytes/point stat?

**Comment by otoolep** [comment]
Will do.

**Comment by jwilder** [comment]
Change looks good otherwise though. :+1:

**Comment by otoolep** [comment]
```
Summary statistics
========================================
Databases converted:                 1
Shards converted:                    14
TSM files created:                   14
Points read:                         40842
Points written:                      40842
NaN filtered:                        0
Inf filtered:                        0
Points without fields filtered:      10
Disk usage pre-conversion (bytes):   4521984
Disk usage post-conversion (bytes):  75374
Reduction factor:                    99%
Bytes per TSM point:                 1.85
Total conversion time:               166.467052ms
```

**Comment by jwilder** [comment]
Nice. :+1:

**Comment by toddboom** [comment]
this is awesome.

**Pull request merged**
