### PR TITLE
Update influx_tsm README with information about shard permissions

### PR DESCRIPTION
**Pull request by rossmcdonald**
I also made minor tweaks to the formatting, but the warning is [here](https://github.com/influxdata/influxdb/compare/ross-influx-tsm-doc-update?expand=1#diff-d60883eeecee971a66d53ce474fddfb0R93).

/cc @joelegasse

### CODE REVIEW

**Comment by joelegasse** [comment]
My only concern is that the `influxdb` user in your updated example probably won't be able to write to a directory owned by the user running the `mkdir` command.

**Comment by rossmcdonald** [comment]
Good point. I've updated it to use `/tmp/influxdb_backup` instead of `~/influxdb_backup`. Writing to `/tmp` as the `influxdb` user worked for my local Ubuntu test box, but let me know if you have any other concerns.

**Comment by joelegasse** [comment]
My concern about using `/tmp` is that it's meant for temporary files, and is often either an in-memory filesystem (`tmpfs`) or wiped on restart. Perhaps just change the `mkdir` command to `mkdir -m 0777 backups`, and add a note, either a comment on the line or before it that states the `influxdb` user needs full permissions in that directory.

**Comment by rossmcdonald** [comment]
@joelegasse Good point. I changed it to `/path/to/influxdb_backup` so the user can decide where they want to place the backup. I also added the `mkdir -m 0777` and a note that the `influxdb` user needs to have full access to the backup directory.

**Comment by joelegasse** [comment]
LGTM

**Pull request merged**
