### PR TITLE
CLI Option to Connect without HTTPS Verifica…

### PR DESCRIPTION
**Pull request by mglazer**
The V2 client code supports this, however, the V1 client code didn't,
and the argument to support this just had to be added to the CLI

### CODE REVIEW

**Comment by dgnorton** [comment]
@mglazer have you signed the CLA?  https://influxdb.com/community/cla.html

**Comment by dgnorton** [comment]
+1 after signing CLA

/cc @corylanou

**Comment by mglazer** [comment]
Yup, I just have to get employer sign off and then you'll have it.

On a side note, when I originally submitted this, the CircleCI build failed. I deleted the pull request and then resubmitted the PR right afterwards (with no source changes), and it passed. I'm unsure if this was a flaky test or not, but might be something to look out for. 

Unfortunately, CircleCI seems to have a retention policy on builds, so the build output is no longer available.

**Comment by dgnorton** [comment]
@mglazer sounds good.  Just comment on this issue once the CLA is signed, we'll get one more reviewer to take a look, and then get it merged.  Re CircleCI, we've had some issues with flaky tests, which we're working on.  If it pops up again and looks like a real problem related to this change, we'll open a new issue for it.  Thanks for your help!

**Comment by mglazer** [comment]
CLA signed. Sorry about the delay. Thanks for taking a look!

**Comment by Ormod** [comment]
Any chances of getting this merged, been sitting in the queue for a while. Would remove the need to have a custom build for me.

**Comment by jwilder** [comment]
:+1:

**Pull request merged**
