### PR TITLE
correct handling of env overrides for scalar slice elements

### PR DESCRIPTION
**Pull request by jonseymour**
- [ ] CHANGELOG.md updated
- [X] Rebased/mergable
- [X] Tests pass
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

This is a backport of a fix to cmd/influxd/run/config.go that was applied to a fork of the same code in influxdata/kapacitor.

As it happens, influxdb doesn't seem to use any scalar arrays or slices - it does have slices of
structs - but if it ever did introduce such arrays or slices then env overrides would not work for them. This change pre-emptively fixes the issue in the same way it was fixed in kapacitor - see https://github.com/influxdata/kapacitor/pull/350

Signed-off-by: Jon Seymour <jon@wildducktheories.com>

### CODE REVIEW

**Comment by jonseymour** [comment]
@offlinehacker here's the change to influx although it isn't actually needed right now.

**Comment by e-dard** [comment]
Hi @jonseymour 

> here's the change to influx although it isn't actually needed right now.

Can you clarify that?

Is this fix still needed. I think some of the env stuff has changed since March.

**Comment by jonseymour** [comment]
Hi @e-dard.

The issue is a latent flaw in the configuration parser. The flaw currently isn't demonstrable because the influxd configuration does not contain arrays within sections. This is most easily explained by using this snippet from the kapacitor configuration which does use arrays within sections.

```
[[influxdb]]
  enabled = true
  name = "default"
  default = false
  urls = ["http://localhost:8086"]
```

The flaw in the kapacitord parser has been fixed. Since that was derived from the influxd parser, I back ported the fix from there to here.

I will check whether the latent issue still exists (by putting some dummy arrays into the configuration) and if it is still an issue I'll rebase my fixes. Otherwise, I'll close this PR.

**Comment by jsternberg** [comment]
This PR needs to be updated. I'm going to close this for now since we haven't been able to merge it, but if you rebase and comment, I'll reopen it for review. Thanks.

**Pull request closed without merging**
