### PR TITLE
Add several backports to 1.6

### LINKED ISSUE #10000: Features to backport for 1.6
A couple of items that should be back-ported to 1.6:

 - [ ] https://github.com/influxdata/influxdb/pull/9982  WAL flush fix
 - [ ] https://github.com/influxdata/influxdb/pull/9972  compact cache fix
 - [ ] https://github.com/influxdata/influxdb/pull/9970 SHOW TAG KEYS perf regression
 - [ ] https://github.com/influxdata/influxdb/pull/9967 Prometheus remote read endpoint

### PR DESCRIPTION
**Pull request by jacobmarble**
Fixes #10000

### CODE REVIEW

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by e-dard** [comment]
@jacobmarble there are bunch of other dependencies that need to go into `Godeps` I think. Mainly from `klauspost`. I think they were missed off of #9856. You can cherry pick https://github.com/influxdata/influxdb/pull/9983 in I think to sort it.

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by jacobmarble** [comment]
`dep ensure` makes no change to `Gopkg.lock`.

**Comment by jacobmarble** [comment]
@e-dard PTAL

**Pull request merged**
