### PR TITLE
tsm: cache: ensure all statistics are initialised on cache creation.

### PR DESCRIPTION
**Pull request by jonseymour**
The intent of this change is to ensure that all statistic fields of the
resulting tsm1_cache measurement are initialized on initialization of
the cache. That way, any consumer of those measurements doesn't
have to deal with the null case.

Signed-off-by: Jon Seymour <jon@wildducktheories.com>

### CODE REVIEW

**Comment by jonseymour** [comment]
@mark-rushakoff Turns out this is more than a nice to have. I was expecting the snapshot related stats to start to appear after 1 hour when the cold limit kicks in, but they didn't for reasons I don't completely understand, but probably has something to do with all fields not being initialized on the first write into the tsm1_cache measurement. In any case, I think justification in the commit message is sufficient.

**Comment by jonseymour** [comment]
It appears the reason the new fields were not created as expected after 1 hour is that relatively idle _internal shards are not compacted (as expected) on an hourly cycle. I'll double check that this is intended behaviour and if not, raise an a seperate issue.

**Comment by jonseymour** [comment]
Compaction only occurs after 1 hour if there are no writes into the WAL log for 1 hour - for shards that are being written slowly but persistently, the first time a compaction trigger will be the size threshold, not the time threshold. So, my expectation about compaction timing was incorrect. I think the current behaviour is reasonable, since it will lead to better TSM compression. In any case all of this is irrelevant to the justification for this commit.

**Comment by mark-rushakoff** [comment]
I was initially trying to avoid writing separate functions for modifying `statMap`, as we seem to be modifying stats "inline" everywhere else. However, given how many stats we're handling here, and given how important it is to get instrumentation correct, separate functions in this case make sense to me.

Up-front initialization of rarely-updated stats also makes sense to me. I wonder if we're approaching the point where we need a "smarter" wrapper around expvar.

**Pull request merged**
