### PR TITLE
Ensure precision flag is respected in CLI

### LINKED ISSUE #5127: CLI does not respect `precision=rfc3339` flag.
```
⇒  influx -precision='rfc3339'
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9
InfluxDB shell 0.9
> use scratch
Using database scratch
> select * from cpu
name: cpu
---------
time			value
1450209026980437426	1

>
```

While `precision` can be adjusted once in the interactive mode, if it's passed as a flag and the value is `rfc3339`, the value is not modified appropriately for the server (i.e., it's not changed to the empty string).

### PR DESCRIPTION
**Pull request by e-dard**
Fixes #5127.

This ensures that precision is correctly modified when using the CLI in interactive mode.

### CODE REVIEW

**Comment by otoolep** [comment]
+1, thanks @e-dard 

@corylanou

**Comment by otoolep** [comment]
@e-dard -- any chance you can rebase?

**Comment by otoolep** [comment]
Great, thanks @corylanou.

**Comment by e-dard** [comment]
@otoolep :shipit:

**Comment by otoolep** [comment]
Thanks @e-dard

**Pull request merged**
