### PR TITLE
Support the deprecated [collectd] and [opentsdb] sections temporarily

### PR DESCRIPTION
**Pull request by jsternberg**
Performs an automatic search and replace on these sections of the
configuration file so they work for the 0.13 release. Will be removed
for 1.0.

### CODE REVIEW

**Comment by jwilder** [comment]
Can you add a test case for this?  We have lots in various `config_test.go` files.

**Comment by jsternberg** [comment]
Added a test case.

**Comment by jwilder** [comment]
👍 on green.

**Comment by rossmcdonald** [comment]
@jwilder @jsternberg Is there a reason why this PR was only applied to `0.13`? This means that anyone upgrading to > 0.13 from < 0.12 will have broken configs.

**Comment by jwilder** [comment]
@rossmcdonald Not that I know of.  Should be on both 0.13 and `master`.

**Comment by jsternberg** [comment]
We haven't merged the 0.13 branch back to master yet. I figured it would be fine to wait a day. We can do that now though if it's needed urgently.

**Comment by rossmcdonald** [comment]
@jsternberg Ah, you're right, nevermind. I forgot we were planning on merging all of these back into master. Please disregard.

**Pull request merged**
