### PR TITLE
Proper password field. Fix #7285.

### LINKED ISSUE #7285: Admin interface: the password is visible and gets stored in the autofill form data
image

### PR DESCRIPTION
**Pull request by dandv**
This should let the admin interface integrate with the browser's password manager.

### CODE REVIEW

**Comment by jsternberg** [comment]
Can you amend the commit with a changelog entry that gives yourself credit? See other examples in the changelog where it says `Thanks`.

Thanks!

Also, just a tip, GitHub won't link issues unless the text is in the body. It doesn't look at titles so you want to put the text at the end of your description.

Fixes #7285.

**Comment by jsternberg** [comment]
/cc @toddboom 

(I deleted a previous comment, got the wrong Todd because I remembered the wrong username)

**Comment by toddboom** [comment]
Looks like the CLA is signed.

@dandv Thanks for the fix!

**Comment by toddboom** [comment]
Also, AppVeyor failed on `TestServer_Query_DefaultDBAndRP`, which can't possibly be related.

**Comment by dandv** [comment]
Thanks for the merge!

@jsternberg: OK to credit myself in the changelog for the next PR, hopefully something more significant?

**Comment by toddboom** [comment]
@dandv already took care of it, should be in master right now.

**Pull request merged**
