### PR TITLE
Check FieldCodec f in FieldCoded.Fields()

### LINKED ISSUE #6294: panic running influx_inspect info
Running ```influx_inspect info```

gives me 
```
influx_inspect info
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00001.wal, size 1077
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00002.wal, size 169812
[filestore] 2016/04/12 23:34:56 /Users/seif/.influxdb/data/stress/default/2/000000001-000000001.tsm (#0) opened in 7.417241ms
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/stress/default/2/_00006.wal, size 0
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00003.wal, size 43295
[cacheloader] 2016/04/12 23:34:56 reading file /Users/seif/.influxdb/wal/_internal/monitor/1/_00006.wal, size 0
[tsm1] 2016/04/12 23:34:56 /Users/seif/.influxdb/data/_internal/monitor/1 database index loaded in 556.748µs
[tsm1] 2016/04/12 23:34:57 /Users/seif/.influxdb/data/stress/default/2 database index loaded in 535.600122ms
Shards: 2, Indexes: 2, Databases: 2, Disk Size: 170, Series: 0

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb8c51]

goroutine 1 [running]:
panic(0x52f420, 0xc8200120e0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/influxdb/tsdb.(*FieldCodec).Fields(0x0, 0x0, 0x0, 0x0)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/tsdb/shard.go:846 +0x41
main.cmdInfo(0xc8200dc860, 0x15)
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/info.go:65 +0x1019
main.main()
	/Users/seif/Projects/go/src/github.com/influxdata/influxdb/cmd/influx_inspect/main.go:51 +0x56d
```

### PR DESCRIPTION
**Pull request by seiflotfy**
If FieldCodec f is nil return nil when FieldCoded.Fields() is called.

Fixes #6294

### CODE REVIEW

**Comment by corylanou** [comment]
I'm fine with the fix as long as it's possible that `f` could be nil.  It feels like there is a check upstream even further we should of had.  @jsternberg might have a better idea of if this is the right fix or not.

**Comment by seiflotfy** [comment]
its either that or i can check before the for loop
https://github.com/influxdata/influxdb/blob/master/cmd/influx_inspect/info.go#L64
```go
if codec == nil {
    continue
}
```

**Comment by corylanou** [comment]
I'm fine with the original fix, my only concern is that we aren't hiding a bug somewhere else.  I would like to know that before closing this one is all. This is a valid fix of course, but I don't want it to introduce a silent bug as a result.

**Comment by jsternberg** [comment]
I think it would be better to check for this at the place of use rather than inside of the method itself, but I'm not really familiar with this code. @benbjohnson or @jwilder will likely know more than me.

**Comment by benbjohnson** [comment]
It looks like it's probably looking up a measurement that is in the shard's meta data but doesn't have points in the shard. I'd rather see the `continue` fix implemented since this error is isolated to `influx_inspect`:

https://github.com/influxdata/influxdb/pull/6295#issuecomment-209152675

**Comment by seiflotfy** [comment]
@benbjohnson @corylanou @toddboom once this passes can someone merge it. Its not a big change but it helps. :D

**Comment by benbjohnson** [comment]
@seiflotfy I resolved the CHANGELOG conflict and merged it in. Thanks!

**Comment by benbjohnson** [comment]
Also, the build failure is just on the Windows CI which has been flakey on one test.

**Comment by seiflotfy** [comment]
thanks guys :smile:

**Pull request merged**
