### PR TITLE
Small influx_stress modification

### PR DESCRIPTION
**Pull request by jackzampolin**

### CODE REVIEW

**Comment by jackzampolin** [comment]
@mjdesa

**Comment by e-dard** [comment]
@jackzampolin am I right in thinking that `NewOutputConfig` is called from another package? Otherwise what's the rationale for this rather than just modifying the fields on the result of a call to `NewOutputConfig`?

**Comment by mjdesa** [comment]
@e-dard `NewOutputConfig` gets called from outside the package.

@jackzampolin I'm not a huge fan of how this is done. I think we could split this into two functions. One that wraps the flag parsing and another that creates the `*outputConfig`.

**Comment by e-dard** [comment]
@mjdesa OK cool, so if there is a good reason to not export the fields in the config, then I think this is a good example of where functional options would work well. Also, why is `outputConfig` unexported in the first place if it's used outside of the package?

You could do something like this for functional options:

```go
type option func(c *outputConfig)

func WithTags(tags map[string]string) option {
    return func(c *outputConfig) {
        c.tags = tags
    }
}

func NewConfig(options ...option) *outputConfig {
    var c := &outputConfig{}

    // Do standard setup and/or defaults of config here
    // ...
    // ...

    // Apply any options.
    for _, opt := range options {
        opt(c)
    }
    return c
}
```

Then to use it you would do something like:

```go
// standard config
c := NewConfig()

// fancy config
c := NewConfig(WithTags(map[string]string{"a": "b"}))
```

I just wrote this out so probably got some typos or whatnot in there :smile:

**Comment by mjdesa** [comment]
@e-dard I suppose I could export the type. When it was initially written I had only intended to use it to make calls to `func (o *outputConfig) HTTPHandler()`. I didn't intend for allowing people to set the values on the `outputConfig`. Any thoughts on whether we should export the type, or do things the way you suggest above?

Thanks for looking over things.  :)

**Comment by jackzampolin** [comment]
I would vote for exporting the type!

**Comment by e-dard** [comment]
Exporting the type will be simpler :smile:

**Comment by jackzampolin** [comment]
Closing due to imminent `influx_stress` refactor :smile:

**Pull request closed without merging**
