### PR TITLE
chore: sync latest core

### PR DESCRIPTION
**Pull request by hiltontj**
No issue for this. This brings in changes to the `IoxSystemTable` trait to support query predicates. See https://github.com/influxdata/influxdb3_core/pull/19

### CODE REVIEW

**Comment by hiltontj** [comment]
@mgattozzi I am sorry this is not ready. I need to switch the references in `Cargo.toml`.

**Comment by mgattozzi** [comment]
Ah no worries 😃 I trust you have everything going properly. Just wanted to make sure you weren't blocked

**Comment by mgattozzi** [comment]
I also thought this was the core pr 😅

**Comment by hiltontj** [comment]
Okay, it should be good now! I switched `Cargo.toml` to point at the latest `rev` in `influxdb3_core`.

**Review by mgattozzi — APPROVED** [review]

**Pull request merged**
