### PR TITLE
Support INFLUX_USERNAME and INFLUX_PASSWORD for setting username/password in the CLI

### LINKED ISSUE #6894: influx command: Use environment variable for password
### Feature Request

__Proposal:__

It would be useful to be able to pass the password to the `influx` command via an environment variable.

__Current behavior:__

Must either pass it as an argument, or via STDIN.

__Desired behavior:__

Be able to pass password via environment variable.

__Use case:__

Providing passwords as arguments is insecure as it's visible to anyone with access to the host. Passing via STDIN makes it difficult to pass commands via STDIN. This is important for scripting, being able to do something like:

```
influx <<'EOF'
lots
of
commands
EOF
```

Environment variables are secure, as they are only visible to the the owner of the process, or root.

### PR DESCRIPTION
**Pull request by jsternberg**
Fixes #6894.

### CODE REVIEW

**Comment by jsternberg** [comment]
@phemmer can you give me some feedback on this for #6894? There were a few different ways to implement this. I decided that we would read the username and password from environment variables if they hadn't been overridden previously. I also had it read the environment variable for password after the prompt and to use whatever the prompt said regardless of if it was empty or not.

Thanks for any feedback.

**Comment by phemmer** [comment]
Sounds reasonable to me. The end result is in line with standard behavior observed in other utilities.
config -> environment -> arguments -> prompt

As you mention, there are a few ways to do it. I personally might have put it above the prompt, and eliminated the conditional, letting the prompt overwrite the value. But it's a trivial amount of code so no matter.

**Comment by jsternberg** [comment]
Ok, then I'll add a changelog entry and have it reviewed by someone on the team so we can get this in for 1.1.

The reason why I put the environment code there is because the prompt only comes up with you do `-password` with an empty argument.

**Comment by jsternberg** [comment]
@rkuchan tagged to add documentation.

**Pull request merged**
