### PR TITLE
fix(task): filter tasks by after param

### LINKED ISSUE #11820: Error while retrieving tasks using 'after' or 'user' query params.
Using get tasks endpoint with `after` or `user` query param will return an error:
```
{u'message': u'failed to decode request', u'code': u'invalid', u'error': u'id must have a length of 16 bytes'}
```

- Create couple of tasks using `influx` command:
`./influx task create 'option task = {name:"n_3",every:1h} from(bucket:"b_1") |> range(start: -1h)' --org-id "0364b4fc0d6fa000" -t "OuNJYaSH5Vqdy3Jd8aZ7ID9C3VKynUket8EmzLR3ILNcJpvbjRZFkt1DDnFNoAs1BYEGUuG-zIPUvxYSxVidzA=="`

- Get all of the existing tasks using `influx` command:
`./influx task find -t "OuNJYaSH5Vqdy3Jd8aZ7ID9C3VKynUket8EmzLR3ILNcJpvbjRZFkt1DDnFNoAs1BYEGUuG-zIPUvxYSxVidzA=="`

The above command returns : 
```
ID			Name	OrganizationID		Organization	Status	Every	Cron
0364b59ea340e000	n_1	0364b4fc0d6fa000	test_1		active	1h0m0s	
0364b5e11600e000	n_1	0364b4fc0d6fa000	test_1		active	1h0m0s	
0364b5f13400e000	n_2	0364b4fc0d6fa000	test_1		active	1h0m0s	
0364b5f7ea00e000	n_3	0364b4fc0d6fa000	test_1		active	1h0m0s	
```

- Use get tasks REST API with `after` or `user` query param:
`curl -GET "http://localhost:9999/api/v2/tasks?after='0364b59ea340e000'" -H "Authorization:Token OuNJYaSH5Vqdy3Jd8aZ7ID9C3VKynUket8EmzLR3ILNcJpvbjRZFkt1DDnFNoAs1BYEGUuG-zIPUvxYSxVidzA=="`

The error is returned:
`{"code":"invalid","message":"failed to decode request","error":"id must have a length of 16 bytes"}`

### PR DESCRIPTION
**Pull request by zhulongcheng**
Closes #11820

_Briefly describe your proposed changes:_

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] http/swagger.yml updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by zhulongcheng** [comment]
@mark-rushakoff request a review.

**Comment by mark-rushakoff** [comment]
Thanks @zhulongcheng -- I haven't forgotten about this one yet, but I still need to investigate if this requires enterprise (closed-source) changes to go with it, and if so I need to make those changes. We haven't quite nailed down our process for community changes with enterprise implications yet.

**Comment by goller** [comment]
Hey @zhulongcheng , I'll going through and working through Task backlog.  Do you mind rebasing this?

**Comment by zhulongcheng** [comment]
rebased.

**Pull request merged**
