### PR TITLE
fix(ui): alerting polish

### LINKED ISSUE #14924: Add the ability to view the influxdb_v2 output for telegraf
many people already have telegraf configured for writing data in and they just need to add a new output for influxdb_v2. We need to add a way for the user to view just the output config for telegraf instead of having to create a new config and just pulling the output section.

Maybe just a new button next to the create configuration button that just shows the output section and gives the user the option to copy or download. the name of the downloaded file should be `outputs.influxdb_v2.conf`

image

image

### LINKED ISSUE #14937: on alert page, the highlighted word Check needs to create a check
Anytime the word "Check", "Notification Rule" or "Notification Endpoint" is highlighted and bold, it should be clickable and open a new create modal.

image

### LINKED ISSUE #14941: Reduce size of status message template so most of the rest is visible.
Let's set the height of the message template to be 2 lines of text.

image

### LINKED ISSUE #14945: Reverse the Conditions from Crit to lowest on create check page.
for threshold checks, the order of the check levels should go from CRIT at the top to OK at the bottom.

### PR DESCRIPTION
**Pull request by alexpaxton**
Closes #14937 
Closes #14941
Closes #14945 

Screen Shot 2019-09-05 at 2 38 18 PM

- Add button in "first-time widget"
- Make "first-time widget" darker to ensure contrast with button

endpoint-overlay-polish

- Move type selection to the top of the form
- Group type-dependent options in a panel
- Add default values for URL for all types
- Use Clockface `Alert` to display the error message

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by russorat** [comment]
remove content template from the http one
Name should be "Name this Endpoint"

**Comment by russorat** [comment]
http post should be the only option

**Comment by alexpaxton** [comment]
Screen Shot 2019-09-05 at 2 49 46 PM
Screen Shot 2019-09-05 at 2 52 32 PM

**Comment by alexpaxton** [comment]
Screen Shot 2019-09-05 at 3 36 02 PM

Shrunk the message field to `90px`

**Comment by alexpaxton** [comment]
Screen Shot 2019-09-05 at 3 45 04 PM

Reversed the order of the thresholds here

**Pull request merged**
