### PR TITLE
Prevent exponential growth in ~/.influx_history

### PR DESCRIPTION
**Pull request by sczk**
This PR addresses issue #5436

Please note that Influx is using the [Liner](https://github.com/peterh/liner) library for the ReadHistory / AppendHistory / WriteHistory functions.

**THE PROBLEM**: 
When the influx console is started, ReadHistory reads the entire buffer from ~/.influx_history into memory, for [up to 1000 lines](https://github.com/peterh/liner/blob/master/common.go#L65-L96). 

Each time a command is entered into the console, [AppendHistory](https://github.com/influxdata/influxdb/blob/0.10.0/cmd/influx/cli/cli.go#L191) is called. This appends to the history buffer we have in memory which has a [limit of 1000 entries](https://github.com/dbehnke/influxdb-gb/blob/4ee5f88c4f5233e3b98d7885e1347582aacdff70/vendor/src/github.com/peterh/liner/common.go#L118-L131) as well. So far, so good.

Now things start to get hairy. [WriteHistory](https://github.com/influxdata/influxdb/blob/0.10.0/cmd/influx/cli/cli.go#L192) is called each time a command is entered. Not only does this function ignore the HistoryLimit, but it *appends* the history buffer in memory to the file. Additionally, when exit() is issued, WriteHistory writes that entire buffer to ~/.influx_history again. You can see how this will cause the file to quickly grow exponentially... 

**REPRODUCTION**
If you want to reproduce the growth yourself: 

   1. Clear your ~/.influx_history file 
   2. Start influx console and send the exit command.
   3. Start the console again and send the exit command one more time. 
   4. Check ~/.influx_history you'll see it contains the exit command **six** times, instead of twice as expected.

**PROPOSED SOLUTION**: 
On the [liner library example page](https://github.com/peterh/liner/), it looks like they open the historyFile with os.Open (read-only), and then attempt to recreate the file each time using os.Create() before WriteHistory is called. If the file already exists, os.Create() will truncate it. This prevents the growth problem by using WriteHistory as intended. 

I modified the file open function for the ReadHistory call and also closed the handle immediately after finished. I didn't see a need to use defer since the handle to the file won't be reused elsewhere.

I've created a function called saveHistory that calls WriteHistory after clearing the ~/.influx_history file. I added historyFilePath to the CommandLine struct to make this easier. I removed historyFile from the struct since it's no longer used. I replaced the calls to WriteHistory with my saveHistory function.

### CODE REVIEW

**Comment by sczk** [comment]
I also want to mention that I personally don't feel it's necessary to call saveHistory() each time AppendHistory is called when a command is ran. Only updating the history file on exit() / certain signals (ctrl+c) would probably be ideal, but I'm curious to see how others feel on the subject. I wanted to preserve the original history saving logic, so that's why the call is still there.

Keep in mind that this issue was noticed by someone who was piping a lot of data directly into the influx console via a script. I don't know how many people will use the console to do that, but if that's a common scenario then saving the history after each command would probably slow down the processing quite a bit.

**Comment by toddboom** [comment]
@corylanou how's this one look to you?

**Comment by corylanou** [comment]
+1

**Comment by toddboom** [comment]
@sczk awesome, thanks! :+1:

**Pull request merged**
