### PR TITLE
always force the file inside the tarball owned by root

### PR DESCRIPTION
**Pull request by lfarkas**
similar to https://github.com/influxdata/telegraf/issues/1704

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by jwilder** [comment]
@rossmcdonald can you take a look?

**Comment by jwilder** [comment]
@lfarkas Is there an issue logged that this PR fixes?

**Comment by lfarkas** [comment]
@jwilder no there is not.

**Comment by jwilder** [comment]
Can you elaborate on what it is fixing?  It's not clear why this change is needed.

**Comment by lfarkas** [comment]
https://github.com/influxdata/telegraf/issues/2337 see my 3th comment.

**Pull request merged**
