### PR TITLE
Having clause support

### PR DESCRIPTION
**Pull request by chobie**
sorry for delay. I'll write some test cases when I back home. for now this is just place holder

having clause syntax:

```
   group by columns [having CONDITIONS]

example:
  select mean(cpu), host from service group by time(1m), host having top(mean, 10) and host = 'service1'
```
- having clause only supports top and bottom. other aggregate function doesn't support.
  - you can't call top and bottom multiple times. (top(debug, 10) and bottom(debug, 1) is not allowed)
  - top and bottom aggregate functions can't operate with OR operator. (e.g: top(cpu, 10) or host = 'hosta' is failed)

Regarding #183

### CODE REVIEW

**Comment by josepablocam** [comment]
@toddboom Did anything like this make it into v0.9.0? I don't see any thing similar in the current spec

**Comment by beckettsean** [comment]
@josepablocam there is so far nothing like this in the 0.9 line. Since this is a very old issue which references prior versions, can you open a new issue for an 0.9 feature request if this is still interesting to you?

**Comment by zapient** [comment]
Is this supported or planned in the 0.9 series?

**Comment by beckettsean** [comment]
@zapient follow https://github.com/influxdb/influxdb/issues/5266 for details.

**Pull request closed without merging**
