### PR TITLE
Display results of multiple queries in Admin UI, Not just the first query.

### LINKED ISSUE #3503: [feature request] admin UI should show results of all queries, not just the first
In the admin UI, when chaining queries with a semi-colon (`;`), only the first query's results are shown. All results are returned, we just need to parse and display them.

screen shot 2015-07-29 at 11 50 19

### PR DESCRIPTION
**Pull request by Vidhuran**
Fixes #3503

### CODE REVIEW

**Comment by Vidhuran** [comment]
- [✓] CHANGELOG.md updated
- [✓] Rebased/mergable
- [✓] Tests pass
- [✓] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

**Comment by toddboom** [comment]
@Vidhuran Thanks for doing this! PR #5710 just moved the location of the admin files (it now lives under `services`). Would you mind updating your PR to account for the change?

**Comment by Vidhuran** [comment]
@toddboom : Sure , I'll update and rebase.

**Comment by toddboom** [comment]
@Vidhuran I just merged this in - should go out in the final v0.11.0 release. Thanks!

**Pull request closed without merging**
