### PR TITLE
Fix panic when the engine already closed in a shard

### LINKED ISSUE #8739: Panic when dropping database
This is possibly a dupe of #8721. Encountered on a largish database.

```
Aug 24 11:24:33 ip-10-0-237-69 influxd[2449]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 24 11:24:33 ip-10-0-237-69 influxd[2449]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x84fa80]
Aug 24 11:24:33 ip-10-0-237-69 influxd[2449]: goroutine 6520 [running]:
Aug 24 11:24:33 ip-10-0-237-69 influxd[2449]: github.com/influxdata/influxdb/tsdb.(*Shard).DiskSize(0xc425b4e1c0, 0x5, 0xc425b4e1c0, 0xc47190aec8)
Aug 24 11:24:33 ip-10-0-237-69 influxd[2449]:         /go/src/github.com/influxdata/influxdb/tsdb/shard.go:423 +0x30
```

### PR DESCRIPTION
**Pull request by oiooj**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA]

fix #8739 and #8721

### CODE REVIEW

**Comment by oiooj** [comment]
@e-dard The `s.ready()` can't make sure `engine != nil`, it's not safe.

**Comment by e-dard** [comment]
@oiooj ah yes I see what you mean; that looks like it may be an oversight in other places too.

**Comment by oiooj** [comment]
@e-dard Yes, I will fix other places ASAP.

**Comment by oiooj** [comment]
@e-dard Can this PR be merged?

**Comment by e-dard** [comment]
Fixed via #8757.

**Pull request merged**
