### PR TITLE
math.mMin causes serious performance degradations

### PR DESCRIPTION
**Pull request by mohammadali-seifkashani**

### CODE REVIEW

**Comment by mohammadali-seifkashani** [comment]
In issue 20459 it was said that math.mMin had bad performance. So I removed math.mMin and math.mMax from fluxFunctions.ts file and added simple min_two_num and max_two_num functions instead. Those removed functions were not used in the project anywhere and no test was implemented for them.

**Comment by mohammadali-seifkashani** [comment]
I don't know where to implement my two functions!!?

**Comment by timhallinflux** [comment]
addresses #20459

**Comment by wbaker85** [comment]
Since the UI code this PR refers to is no longer in the `influxdb` repository and the underlying issue has been transferred to Flux repo (see: https://github.com/influxdata/flux/issues/3508), I'm going to close this PR out since we won't be able to merge it here.

**Pull request closed without merging**
