### PR TITLE
fix(alerts): remove the cron option from checks/rules

### LINKED ISSUE #15184: Remove cron field from check and notification rule in swagger
We can not currently generate the flux that the check/NR tasks need from a cron interval. Let's remove from swagger definition.

### PR DESCRIPTION
**Pull request by bednar**
Closes #15184

Remove the cron option from checks/rules.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by desa** [comment]
@bednar yup I agree with @ebb-tide We should just remove the cron option from checks/rules

**Comment by ebb-tide** [comment]
https://github.com/influxdata/influxdb/issues/15184

**Comment by bednar** [comment]
Ok, thanks for a clarification

**Comment by bednar** [comment]
I have been change the PR to remove the cron from checks/rules.

**Comment by ebb-tide** [comment]
thanks !

**Pull request merged**
