### PR TITLE
Fix possible deadlock

### PR DESCRIPTION
**Pull request by jwilder**
In a load test env, writes started timing out in and filling up hinted handoff queues.  The traces show a hundreds of write goroutines blocked trying to acquire the `tsdb.Store` read lock.  There were a few other goroutines stuck trying to acquire the `tsdb.Store` write lock in the periodic maintenance goroutine and during expanding sources during a query.

This change removes the maintenance goroutine because it is not used by `tsm` engine and just ends up locking the whole `tsdb.Store` periocially.  This also switches the write lock taken during expanding sources to a read lock since that code only ever reads fields on the `tsdb.Store`.

- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by jwilder** [comment]
cc @benbjohnson

**Comment by joelegasse** [comment]
LGTM :+1:

**Comment by pauldix** [comment]
+1

**Comment by benbjohnson** [comment]
I'm late to the game but :+1: too

**Comment by jwilder** [comment]
Cherry-picked to 0.11

**Pull request merged**
