### PR TITLE
[0.11] fix TypeError when processing empty results in admin UI (#6193)

### PR DESCRIPTION
**Pull request by jonseymour**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

A change to the admin UI prevented the success message being displayed
for empty results. This change restores the original behaviour for
this case.

Signed-off-by: Jon Seymour <jon@wildducktheories.com>

### CODE REVIEW

**Comment by jonseymour** [comment]
See #6195 for a variant of this change that applies against master.

**Comment by jsternberg** [comment]
Is this urgent enough to require a patch release? If not, we can probably close this and just put it into master. We also already cut the branch for the 0.12 release candidate.

**Comment by gunnaraasen** [comment]
@jsternberg We've historically had no issues merging changes to non-core pieces of the database, like the admin UI and CLI, into RC branches. I don't see anything wrong with including this change. We really should explicitly define a policy so there's no confusion in the future.

**Comment by gunnaraasen** [comment]
That said, I didn't notice this was against the 0.11 branch. As @jsternberg mentioned, we're unlikely to cut another minor 0.11 release.

@jonseymour can you open this PR against the 0.12 branch?

**Comment by toddboom** [comment]
Yeah, i agree - this doesn't seem like it's worth cutting another minor release of v0.11. If @jonseymour wants to open this up against the `0.12` branch, we can get it in for the final release this week. I can cherry-pick it back into master after that. Thanks for the fix!

**Comment by toddboom** [comment]
ah, @jsternberg just pointed out the other PR that's already set for master. feel free to ignore my earlier comments. i'll review the master PR and use that one for the `0.12` branch.

**Comment by toddboom** [comment]
As mentioned in the issue, I'm merging this so that the branch is fixed, but we don't currently plan to cut another point release in the v0.11.x line.

**Pull request merged**
