### PR TITLE
Add notes on how to avoid downtime

### PR DESCRIPTION
**Pull request by mjdesa**

### CODE REVIEW

**Comment by mjdesa** [comment]
@beckettsean

**Comment by beckettsean** [comment]
:+1:

**Comment by jsternberg** [comment]
This needs to be rebased so it can pass the unit tests. The error it's getting is one that was fixed in master at some point.

**Comment by beckettsean** [comment]
@jsternberg This is purely edits to a markdown file. Do we really need a green CI run to merge? (Especially if the failure is known and unrelated)

Would it be easier to just close this and open a new PR against master?

**Comment by jsternberg** [comment]
It needs to hit green even if we think that it won't break anything. The change seems to be pushed to the influxdata/influxdb repo though so I should be able to pull it down, rebase, and push it back up so we don't have to wait of @mjdesa.

**Pull request merged**
