### PR TITLE
Patches for 0.13.1

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by jsternberg** [comment]
Please list any patches that need to be backported for 0.13.1 here so I can cherry-pick them into this PR and we'll merge this when we have all of the changes needed for 0.13.1.

**Comment by e-dard** [comment]
@jsternberg https://github.com/influxdata/influxdb/pull/6647 could be put into `0.13.1` since it fixes a panic.

**Comment by jsternberg** [comment]
Cherry picked #6647.

**Comment by pjmyburg** [comment]
Any idea on an ETA for 0.13.1?
#6661 is a bit of a problem for us, but I've been holding off on rolling back to 0.12 as we need the timezone offset functionality that was added in 0.13.

**Comment by beckettsean** [comment]
@jsternberg at this point presumably we should close this in favor of 1.0-beta2, which is a superior release to 0.13.x?

**Comment by jsternberg** [comment]
I think that's reasonable. I'll close this and reopen if @jwilder thinks we should still do a 0.13.1.

**Comment by csulmone** [comment]
I would appreciate a 13.1 release as well.
#6647 just killed a production InfluxDB server in our environment.

**Pull request closed without merging**
