### PR TITLE
chore: changelog updated for 1.7.10 GA

### PR DESCRIPTION
**Pull request by gshif**
Closes #

Describe your proposed changes here.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by hahnjo** [comment]
Right now there's only a tag `1.7.10rc0` and not yet the final release. Is this intentional?

**Comment by gshif** [comment]
Hi Jonas,
That was my mistake, thanks for pointing that out.

Gershon

**Comment by hahnjo** [comment]
> Hi Jonas, That was my mistake, thanks for pointing that out. Gershon

Will this be fixed in the near future? 1.7.10 has an important fix for compactions that I would like to install on our server.

**Comment by gshif** [comment]
@hahnjo, Let me find out when GA is ready to be built.

**Pull request merged**
