### PR TITLE
Include sysvinit-tools as an rpm dependency

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by rossmcdonald** [comment]
👍  LGTM

**Comment by melor** [comment]
Why is this needed? Now the rpm package won't install on systemd-based distros such as Fedora and RHEL7.

**Comment by eduardchernomaz** [comment]
Also, AWS already provides a package `sysvinit` that makes this dependency obsolete:
```
Examining sysvinit-tools-2.88-14.dsf.el7.x86_64.rpm: sysvinit-tools-2.88-14.dsf.el7.x86_64
Cannot install package sysvinit-tools-2.88-14.dsf.el7.x86_64. It is obsoleted by installed package sysvinit-2.87-6.dsf.15.amzn1.x86_64
```

**Comment by rossmcdonald** [comment]
@eduardchernomaz Thank you for letting us know. We have opted to remove the RPM dependency altogether, so this issue will no longer occur with the latest packages.

**Pull request merged**
