### PR TITLE
feat(ci): validate OpenAPI spec

### PR DESCRIPTION
**Pull request by rawkode**
Reference: #15778 

We should know when we're breaking the OpenAPI spec :smile: 

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by mark-rushakoff** [comment]
The current changes to the Circle config are fine by me, but I'm not sure who is best to validate the new .validaterc file.

**Comment by jademcgough** [comment]
Is this blocked on anything?

**Comment by rawkode** [comment]
@jademcgough I'm working through the errors today :+1:

**Comment by rawkode** [comment]
@jademcgough I can't find any rules that really fit our style. I'm going to close this for now, but if you have 30 minutes this week - can we pair and put something together?

**Pull request closed without merging**
