### PR TITLE
Missing hardwareAddr in uuid v1 generation

### PR DESCRIPTION
**Pull request by amallia**
###### Required for all non-trivial PRs
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [ ] [InfluxQL Spec](https://github.com/influxdata/influxdb/blob/master/influxql/README.md) updated
- [ ] Provide example syntax
- [ ] Update man page when modifying a command
- [ ] Config changes: update sample config (`etc/config.sample.toml`), server `NewDemoConfig` method, and `Diagnostics` methods reporting config settings, if necessary
- [ ] [InfluxData Documentation](https://github.com/influxdata/docs.influxdata.com): issue filed or pull request submitted \<link to issue or pull request\>

### CODE REVIEW

**Comment by amallia** [comment]
@jacobmarble I don't think the failure is related to my changes

**Comment by jacobmarble** [comment]
@amallia I restarted the CI builder without checking the failure, just see what happens. Also read through this PR and there's nothing to complain about.

@mark-rushakoff please take a second look at this change. I'll own the merge, just want a second look at this code.

**Comment by jacobmarble** [comment]
@amallia thanks for this PR. Short and clear, fixes an obvious mistake.

Curious, was it causing problems for you?

**Comment by amallia** [comment]
I was just poking around in the codebase and saw this bug and thought it was a good idea to fix it.
I am not using influxdb yet. Happy to find out my PR was appreciated.

**Comment by e-dard** [comment]
This will need a manual `CHANGELOG` entry PR.

**Pull request merged**
