### PR TITLE
Small init.d change

### PR DESCRIPTION
**Pull request by gunnaraasen**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Fixes https://github.com/influxdata/influxdb/issues/3374.

cc/ @rossmcdonald

### CODE REVIEW

**Comment by jsternberg** [comment]
👍

**Comment by rossmcdonald** [comment]
What's the reason for this change? Is InfluxDB not daemonized properly with the current functionality?

**Comment by e-dard** [comment]
@gunnaraasen any update on @rossmcdonald's question?

**Comment by gunnaraasen** [comment]
Thought I saw this behavior before but just tested on a new box and looks like InfluxDB daemonizes properly.

**Pull request closed without merging**
