### PR TITLE
add mode() function & tests

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by jsternberg** [comment]
@agaurav before I merge this, which email do you want to use as the author for this commit? I see @opavader and @agaurav seem to be both you, but with different emails. I want to make sure the commit log has the credit given to the correct GitHub username.

**Comment by jsternberg** [comment]
@jwilder can I also get a thumbs up that this is OK to merge into 1.0 to be released with the next release candidate?

**Comment by agaurav** [comment]
@jsternberg I think i signed the CLA with this account (@agaurav), so please use this.

**Comment by jsternberg** [comment]
Looking at the CLA responses we've gotten, I see you used @agaurav as the GitHub account name, but you used `ashish@archsaber.com` as the email. That email appears to be linked to your other account. Do you want to use that email with the commit or a different email?

Either one is fine with me.

**Comment by agaurav** [comment]
Yeah you can use that.

**Comment by jwilder** [comment]
Looks great @agaurav! This is missing a changelog entry though.

**Comment by jwilder** [comment]
cc @nathanielc

**Comment by agaurav** [comment]
@jwilder https://github.com/influxdata/influxdb/pull/7207 for changelog.
Also, https://github.com/influxdata/docs.influxdata.com/pull/585 for updating the docs.

**Pull request merged**
