### PR TITLE
Fix pathological TSM query case

### PR DESCRIPTION
**Pull request by jwilder**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated

This fixes a pathological query condition cause by and problematic
structuring of TSM files based on how points were written.  The
condition can occur when there are multiple TSM files and a large
number of points are written into the past.  The earlier existing
TSM files must also have points in the past and close to the present
causing their time range to eclipse the later files.

When this condition occurs, some queries can spend an excessive amount
of time merging all the overlapping blocks.

The fix was to constrain the window of overlapping blocks based on
the first one we ran into.  There was also a simple case in the Merge
where we could skip the binary search path and just append the two
inputs.

Locally with a dataset that reproduced the issue.  Query time improvied from **6m53s** **to 4.9s**
### Before

```bash
$ time influx -database test -execute "select count(n) from ctr"
name: ctr
---------
time	count
0	36550000


real	6m52.913s
user	0m0.004s
sys	0m0.007s
```

### After
```bash
$ time influx -database test -execute "select count(n) from ctr"
name: ctr
---------
time	count
0	36550000


real	0m4.870s
user	0m0.004s
sys	0m0.006s
```

@benbjohnson

### CODE REVIEW

**Comment by benbjohnson** [comment]
`s/pathalogical/pathological/g`

**Comment by benbjohnson** [comment]
@jwilder Which part is the actual fix? Most of it seems to be converting to use `tmpl`.

**Comment by benbjohnson** [comment]
@jwilder I would suggest renaming `iterator.gen.go.tmpldata` to just `tmpldata` and have all the `tmpl` files share it.

**Comment by jwilder** [comment]
@benbjohnson I tried using a shared tmpldata file, but I need an "empty" case that breaks the iterator template.  See: https://github.com/influxdata/influxdb/pull/6725/files#diff-8d638cad869bc34b4242903d683f0fe4R3

**Comment by jwilder** [comment]
The actual fix is related to: https://github.com/influxdata/influxdb/pull/6725/files#diff-5a96dfa80c056f0089d0a9bb1cc9d63cR167 and the places where `minT` and `maxT` are now used.

**Comment by jwilder** [comment]
The merge fix are these two conditions: https://github.com/influxdata/influxdb/pull/6725/files#diff-5951f90f66e625adf49880f68dfd1da9R101

**Comment by benbjohnson** [comment]
:+1:

**Pull request merged**
