### PR TITLE
refactor: remove arrow_batchtes_to_json

### PR DESCRIPTION
**Pull request by JeanArhancet**
This PR addresses the first part of issue #24981. It replaces the usage of `&arrow_json::writer::record_batches_to_json_rows(batches.as_slice())?` with `arrow_json::ArrayWriter` in the file `influxdb3_server/src/http.rs.`

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by hiltontj — CHANGES_REQUESTED** [review]
The change itself looks solid, but I think that this is a good opportunity to add some more tests for JSON formatted output, to guard against regressions.

I took a look around and from what I see the only test that confirms that this works is here: https://github.com/influxdata/influxdb/blob/a5eba2f8f25d8a6dd1ea9237a7278427853473d4/influxdb3_server/src/lib.rs#L343-L355

Can you add an end-to-end `query` test that verifies this functionality? We have several such tests in [this file](https://github.com/influxdata/influxdb/blob/a5eba2f8f25d8a6dd1ea9237a7278427853473d4/influxdb3/tests/server/query.rs), but the existing tests for the `v3` query APIs only assert on pretty formatted table output. You could add a test for JSON formatted output. There is an example of asserting on JSON output for the v1 query API here: https://github.com/influxdata/influxdb/blob/a5eba2f8f25d8a6dd1ea9237a7278427853473d4/influxdb3/tests/server/query.rs#L516-L517

**Comment by JeanArhancet** [comment]
> The change itself looks solid, but I think that this is a good opportunity to add some more tests for JSON formatted output, to guard against regressions.
> 
> I took a look around and from what I see the only test that confirms that this works is here:
> 
> https://github.com/influxdata/influxdb/blob/a5eba2f8f25d8a6dd1ea9237a7278427853473d4/influxdb3_server/src/lib.rs#L343-L355
> 
> Can you add an end-to-end `query` test that verifies this functionality? We have several such tests in [this file](https://github.com/influxdata/influxdb/blob/a5eba2f8f25d8a6dd1ea9237a7278427853473d4/influxdb3/tests/server/query.rs), but the existing tests for the `v3` query APIs only assert on pretty formatted table output. You could add a test for JSON formatted output. There is an example of asserting on JSON output for the v1 query API here:
> 
> https://github.com/influxdata/influxdb/blob/a5eba2f8f25d8a6dd1ea9237a7278427853473d4/influxdb3/tests/server/query.rs#L516-L517

I've added an end-to-end test. WDYT?

**Review by hiltontj — APPROVED** [review]
LGTM! Thank you @JeanArhancet 🚢

**Comment by hiltontj** [comment]
@JeanArhancet I will follow up on the build failures with my team on Monday. Those may not be related to your PR.

**Comment by hiltontj** [comment]
Hey @JeanArhancet I think that the fix for the build was recently merged to `main` in https://github.com/influxdata/influxdb/pull/25044, but that may have merged after you created your fork.

Can you try updating your fork and rebasing off `main`?

**Comment by JeanArhancet** [comment]
> Hey @JeanArhancet I think that the fix for the build was recently merged to `main` in https://github.com/influxdata/influxdb/pull/25044, but that may have merged after you created your fork.
> 
> 
> 
> Can you try updating your fork and rebasing off `main`?

Done @hiltontj

**Pull request merged**
