### PR TITLE
chore: enable CLAsee checker

### PR DESCRIPTION
**Pull request by GeorgeMac**
This enabled the clasee github action which checks the influxdata CLA on PR open.

If the contributor has not yet signed the CLA it fails the PR build.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] http/swagger.yml updated (if modified Go structs or API)
- [x] Documentation updated or issue created (provide link to issue/pr)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by GeorgeMac** [comment]
@goller absolutely. You thinking README / docs folder or wiki?

**Comment by GeorgeMac** [comment]
@e-dard sweet on it

**Comment by e-dard** [comment]
@timhallinflux are you OK with the new license content added to the `README`?

**Comment by GeorgeMac** [comment]
If it is any help I lifted the second paragraph of this readme change verbatim from our CLA page.

**Comment by GeorgeMac** [comment]
holding off on this because I overlooked access to secrets by forks

**Pull request closed without merging**
