### PR TITLE
Merge influx_tsm conversion fixes into master

### PR DESCRIPTION
**Pull request by jonseymour**
Resolves a merge conflict between #5675 and #5570.

This is an alternative (dual, even) of #5677 which has the advantage of
also incorporating a useful change to influx_tsm into master.

With this change, any future merge of 0.10.0 into master will be conflict free
with respect to the conflicting changes above.

**Updated:** this PR is intended to merge changes to influx_tsm that are required to fix issues with influx_tsm which cause data loss when converting shards that were created with versions of influx prior to v0.9.3. The fixes have already been applied to the maintenance branch 0.10.0 but are not currently in master. This PR resolves a merge conflict between those changes (62711ba) and a change already in master (#5570). It does no other thing than that.

### CODE REVIEW

**Comment by jonseymour** [comment]
Image of merge resolution

**Comment by jwilder** [comment]
@jonseymour Our process is not to merge release branches into master.  We do the opposite and commit to master and selectively backport fixes to release branches when it makes sense to do patch releases.  In general, PRs should always be against master so that fixes will be part of the next release.

I can't actually tell what this PR is fixing other than trying to resolve a merge conflict issue for a branch merge that we won't actually perform.  Is there a functional change here that is not in master?

**Comment by jonseymour** [comment]
The functional change is the TSM conversion issue that I analysed last week. That has been merged into 0.10.0 by @joelegasse but hasn't been merged into master yet. This PR does that and nothing else.

**Comment by jonseymour** [comment]
BTW I understand the back port rule. Fixes developed against the latest release tag should merge cleanly with the maintenance branch for that tag and will usually merge cleanly into the tip of master. If they dont't then merges like this PR are necessary. The requirement to merge cleanly with master is a good one, but the tip of master usually isn't the best base commit to choose when creating a fix  The reason is that fixes developed against the tip of master can almost never be trivially applied to a maintenance branch because they drag in all of master's history. Fixes based in the latest release tag can often be "back ported" with nothing more than a normal merge. All of my open PRs, for example, merge cleanly with 0.10.0 and master because I chose v0.10.0 as the base commit. This is the one exception that didn't, but even then the resolution was trivial - just resolve a merge between the two commits that actually conflicted.

**Comment by jonseymour** [comment]
ps: 1000 apologies if any of the above makes it appear like I was trying to provide a seminar on the virtues of inhaling eggs with a straw. My love of git sometimes gets the better of me :-)

**Comment by joelegasse** [comment]
@jonseymour Sorry that this fix was a mess (from a git perspective), but the changes were applied ,along with correcting the typo, here: https://github.com/influxdata/influxdb/pull/5704

**Pull request closed without merging**
