### PR TITLE
Change protobuf package names to avoid clashes

### LINKED ISSUE #6211: Influxd config error:  proto: duplicate proto type registered: internal.IteratorStats
I generate config files using `Influxd config > influxdb.conf` to modify the data storage path. With the latest master (https://github.com/influxdata/influxdb/commit/c2ac8c85b56132b4372735e9628bd7eb04e66162 ), this command is failing in both Linux and Windows.

```go
$ influxd config > influxdb.conf
2016/04/05 08:16:05 proto: duplicate proto type registered: internal.IteratorStats
```

The command itself generates config output, but there is this error generated. Not sure if the config is complete or not.

### PR DESCRIPTION
**Pull request by e-dard**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Fixes #6211.

> For the following description `pb-package` refers to the `package foo` declaration at the top of a protofbuf package, and `package` refers to a Go package.

Every `pb-package` in influx is named `internal`. This is fine if none of the definitions are duplicated anywhere, but it's now the case that they are (`IteratorStats` appears in the `cluster` proto spec and the `influxql` proto spec.

I think it would be better if `pb-packages` were separate from each other, so we don't get clashes like this. A simple way to do this, while allowing us to still consistently refer to the generated types as `internal.Foo` is to use an `internal` alias in front of the import definition. 

Commit  dfee15b fixed #6211 and prevents any further clash, but I think we should just scope all of the `pb-packages` appropriately, so _none_ are referred to as `internal`, then we just do, for example: 

```go
import (
        internal "github.com/influxdata/influxdb/tsdb/internal"
)
```

and we can continue to refer to all the generated types as, e.g., `internal.MeasurementFields` even though they're defined in the generated internal package `tsdb` and not `internal`. I've updated the other packages in 184257a.

/cc @corylanou @benbjohnson since you've both had to fiddle with protobuf clashes at one point or another I think!

### CODE REVIEW

**Comment by jsternberg** [comment]
Doesn't this stop the internal packages from being internal? Or are they still restricted from being used outside of the parent package?

**Comment by e-dard** [comment]
@jsternberg no they remain internal packages, since any package under an `internal` directory is treated as such, no matter what its name is.

**Comment by jsternberg** [comment]
Looks fine to me, but I think this would change the wire protocol for the RPC messages because of the name change. I think it's probably fine, but I want to wait for someone more familiar with clustering to confirm that.

**Comment by benbjohnson** [comment]
@e-dard I like the alias idea. Can we change the package name to `cluster_internal` so it's clearer in stacktraces that it's not the `cluster` package?

I agree with @jsternberg that it might break the wire protocol. Definitely worth checking into that.

**Comment by e-dard** [comment]
@benbjohnson OK I'll update. Maybe this is one to keep open until we're closer to `0.13` and we can make a more-informed decision about wire protocol issues?

**Comment by jsternberg** [comment]
I like continuing to use the `cluster` package personally since I think of the internal package as a part of the parent. I also think the error messages will be more clear, but it's not that big of a deal.

@e-dard we likely need to merge something to fix the name clash decently soon since this currently causes an error message to be printed when starting the application from master.

**Comment by jsternberg** [comment]
Further testing was done by @joelegasse and he confirmed that changing the names does *not* change the wire format. The names are solely used internally by the Go protobuf implementation.

We are safe to merge this. :+1:

**Comment by jsternberg** [comment]
Cherry-picked this for 0.12.1 in #6256.

**Pull request merged**
