### PR TITLE
Add necessary internal functions to v2 client

### PR DESCRIPTION
**Pull request by parthiv777**

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @parthiv777 -- have you signed the CLA?

@sparrc

**Comment by otoolep** [comment]
@sparrc -- is this PR still valid considering your planned changes?

**Comment by sparrc** [comment]
@otoolep yes but this was based off a pretty old version, needs to be rebased

**Comment by jwilder** [comment]
@parthiv777 Can you rebase?

**Comment by e-dard** [comment]
I'm going to close this out if there is no update in the next couple of days.

**Pull request closed without merging**
