### PR TITLE
Modify the storage service to expose a grpc interface instead of yarpc

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
``````

**Comment by jsternberg** [comment]
This is failing on Windows because of an unrelated error that is happening in the tsdb package. I'm going to merge this since the other unit tests are passing and the one that is failing is a known failure.

**Pull request merged**
