### PR TITLE
build(flux): update flux to v0.180.0

### PR DESCRIPTION
**Pull request by wolffcm**

### CODE REVIEW

**Review by onelson — APPROVED** [review]
:ship:

**Review by onelson — COMMENTED** [review]
Approved before I noticed the test failures :cold_sweat:

**Comment by wolffcm** [comment]
Hmm, I will take a look. It looks like formatter changes, maybe.

**Comment by wolffcm** [comment]
I am restarting the release for other reasons, will open a fresh PR in a bit.

**Pull request closed without merging**
