### PR TITLE
chore(flux): renamed v1 package to schema

### PR DESCRIPTION
**Pull request by sanderson**
The Flux `influxdata/influxdb/v1` package has been replaced by `influxdata/influxdb/schema`. I've updated `fluxFunctions.ts` to reflect that change.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

**Review by alexpaxton — APPROVED** [review]

**Review by russorat — APPROVED** [review]
LGTM

**Comment by danxmoran** [comment]
@sanderson @russorat would this be considered a new feature, or a bug fix for the CHANGELOG?

**Comment by russorat** [comment]
@danatinflux probably bugfix

**Comment by danatinflux** [comment]
@russorat Wrong 'Dan', I'm thinking? 

@danxmoran ^^^^

**Pull request merged**
