### PR TITLE
Merge 1.0 branch

### PR DESCRIPTION
**Pull request by jwilder**
Pull in changes from 1.0.2

### CODE REVIEW

**Comment by sebito91** [comment]
Tried taking this patch just now against current HEAD and getting conflicts. Does this need a rebase? Would be great to get these changes in :D

**Comment by jwilder** [comment]
@sebito91 Rebased.

**Comment by jwilder** [comment]
@jsternberg can you take a look?

**Comment by sebito91** [comment]
Merge succeeded, thank you!

**Comment by jsternberg** [comment]
Was this rebased? That will mess up the merge tree if it was and we need to resolve the conflicts if we want a clean merge tree.

**Comment by jwilder** [comment]
@jsternberg It was rebased.  I can just do the merge of 1.0 into master branch instead.

**Comment by jsternberg** [comment]
Yea, I think it would be better to perform a merge instead.

**Comment by jwilder** [comment]
@jsternberg Re-pushed w/ just a merge of `1.0` branch.

**Pull request merged**
