### PR TITLE
Reduce pool size, change WAL writers default

### PR DESCRIPTION
**Pull request by rubycut**
Big pool can lead to huge memory usage in certain loads.

See #7640 for detailed discussion.

### CODE REVIEW

**Comment by e-dard** [comment]
@rubycut you need to `gofmt` your code.

**Comment by rubycut** [comment]
@e-dard , done.

**Comment by ambatigan** [comment]
Tried v1.2.1-rc5 after building the binaries... Still seeing the RES memory increasing gradually to a greater extent and finally influxdb crashes....

**Comment by jwilder** [comment]
@ambatigan Please log a new issue and the attach the information requested in the [issue template](https://github.com/influxdata/influxdb/blob/master/.github/ISSUE_TEMPLATE.md).

**Pull request merged**
