### PR TITLE
Fix aux iterators to respect early closing

### LINKED ISSUE #5974: [0.11.0] Arbitrary math on fields causes panic.
In the case of arbitrary math on fields however, I think the panic is different. I'm seeing this for arbitrary math:

```
[query] 2016/03/09 23:22:40 SELECT value + lol FROM db."default".cpu
[0xc820992420]
panic: send on closed channel

goroutine 106 [running]:
panic(0x6c8640, 0xc8209de3f0)
	/usr/local/share/go/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/influxdb/influxql.auxIteratorFields.send(0xc8207aa740, 0x2, 0x2, 0x1412e30, 0xc82055e420)
	/Users/edd/Documents/projects/golang/src/github.com/influxdata/influxdb/influxql/iterator.go:354 +0xdab
github.com/influxdata/influxdb/influxql.(*floatAuxIterator).stream(0xc820634870)
	/Users/edd/Documents/projects/golang/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:625 +0x107
created by github.com/influxdata/influxdb/influxql.(*floatAuxIterator).Start
	/Users/edd/Documents/projects/golang/src/github.com/influxdata/influxdb/influxql/iterator.gen.go:588 +0x35
```

### PR DESCRIPTION
**Pull request by jsternberg**
Fix aux iterators to respect early closing

The primary input iterator for an aux iterator would continue trying to
send points to a closed channel even after an aux iterator had already
been closed.

This changes the aux iterators to use sync.Cond instead of channels and
lower level syncing primitives for handling buffered input/output.

Fixes #5974.

### CODE REVIEW

**Comment by jsternberg** [comment]
@benbjohnson a modification to the channel iterators spawned from an AuxIterator. They need some way to signal that they're supposed to stop reading from the channel early so they block when the iterator is open but return the buffered point or nil when they are closed.

Not sure if the number of selects would effect performance.

**Comment by benbjohnson** [comment]
@jsternberg It seems like it would be simpler to add a `closing` channel that would be closed instead of closing the `c` channel. Then `select` between the two and exit if `closing` is closed.

**Comment by jsternberg** [comment]
I tried that, but it resulted in a lot of ugly complexity because of the specific rules for it. Channels are a great abstraction sometimes, but they work pretty badly for this use case. In the setter I had to do this:

```
select {
case itr.c <- p:
case <-done:
    return false
}
```

That method required allocating a new point even if that point would never be sent, so I then changed it to this:

select {
case <-done:
    return false
default:
}

select {
case itr.c <- p:
case <-done:
    return false
}
```

Then `Next()` had to be like this:

```
select {
case p := <-itr.c:
    return p
case <-done:
    select {
    case p := <-itr.c:
        return p
    default:
        return nil
    }
}
```

This is because it had to drain the iterator for next, but a closed iterator will always be the one to be chosen when a select is used. It seemed more simple to just use the lower level aspects especially in such a sensitive portion of the code. The channels are already hiding a bunch of mutex and condition locking anyway.

That's my rationale for this anyway since none of the locks are hidden.

**Comment by benbjohnson** [comment]
:+1:

**Pull request merged**
