### PR TITLE
Tolerate b1 shard index inconsistencies during TSM conversion

### PR DESCRIPTION
**Pull request by jonseymour**
These commits address data loss issues caused by a shard index inconsistency caused by a defect that was fixed (3348dab) in version 0.9.3. The data loss problem this inconsistency caused was reported with #5606. 

The changes have been tested with an instance of a 47GB database of 32 shards and 1.1B points. Prior to the fix, around 600M points (4GB) were unexpectedly dropped from the converted database. With the fix, the full 1.1B points were preserved resulting in a converted database size of 8.8GB.

Feedback is welcome about whether the list of orphaned series should be dumped to the output and whether the tracker should be used to to dump the warning messages.

Other areas of improvement might be the means that the RepairIndex configuration is associated with the b1 reader. Should I pass this as a parameter to the reader constructor or pass an reader specific options/configuration object?

A similar change should probably also be made to the bz1 reader, but I didn't have a test case I could use to verify the integrity of such a change. I am happy to extend the change to the bz1 reader if that is desired.

**It is probably worth noting that any influx database that has data that was created with a version less than 0.9.3 may be susceptible to silent data loss during TSM data conversion until this fix is applied.**

### CODE REVIEW

**Comment by jwilder** [comment]
@joelegasse can you take a look?

**Comment by joelegasse** [comment]
@jonseymour Do you have an example of how to create the orphaned series in the old versions? I'd like to see if bz1 is similarly affected.

As far as your code, the change looks good, but I would suggest a few things:
- Modify the constructor of `b1.Reader`, rather than adding an exported field
- Change the usage text of the command line flag to remove the repetition, maybe "Determines how to handle orphaned series: 'fail', 'repair', or 'ignore'"

But those might be moot depending on the answer to a question... For the "orphaned" series, are they query-able if left in their current shards? If so, is there any reason we would _want_ to ignore/drop the data during the conversion? In other words, why would we want to make this configurable, instead of just automatically repairing?

**Comment by joelegasse** [comment]
@jonseymour After talking with the team, it looks like there's no reason not to just scan for all the series and include them, completely ignoring the index. I'll create another PR that will handle both `b1` and `bz1` shards.

Thank you for digging in to this and figuring out what was going wrong. :-)

**Comment by joelegasse** [comment]
I've incorporated, simplified, and extended your changes to both `b1` and `bz1` in #5665, so I'm going to close this PR.

**Pull request closed without merging**
