### PR TITLE
Update help and remove unused config options from the configuration file

### PR DESCRIPTION
**Pull request by jsternberg**
Normalize the output for the various help options so they all follow the
same format and display all relevant options.

Removing some of the unused config options from the configuration file
and updating the help documentation. Removing some remaining references
to clustering within the open source version.

### CODE REVIEW

**Comment by gunnaraasen** [comment]
LGTM

**Comment by e-dard** [comment]
Looks fine to me, but I'm wondering what peoples' thoughts are on deprecating (warning) options first, rather than taking them away, since this change will break anything that are using these options.

**Comment by jsternberg** [comment]
The options removed from the configuration shouldn't be in use anymore. TOML should just ignore any entries that it doesn't know so there shouldn't be any problem with taking away options.

**Comment by e-dard** [comment]
@jsternberg sorry I was talking about flags not options. Though looks like you only altered the usage message anyway?

**Comment by jsternberg** [comment]
Ah, that makes a lot more sense. I only removed the help message, but I still define the flag so that existing servers will still work if they use that option. It's just that the option doesn't do anything. Maybe we should add a deprecation message while that value is unset, but I think we can do that in a later release since I don't want to introduce a deprecation message before 1.0. It's not a big deal to just define the flag and ignore the result as long as we don't advertise that it does something (when it doesn't).

Thoughts? Should I add a deprecation message and plan to delete it in a later release?

**Comment by jsternberg** [comment]
I'll merge this as-is and add the deprecation message later if we think it's a good idea.

**Pull request merged**
