### PR TITLE
Move to Go 1.6.2

### PR DESCRIPTION
**Pull request by rossmcdonald**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Fixes https://github.com/influxdata/influxdb/issues/6511

### CODE REVIEW

**Comment by jwilder** [comment]
Need to update this? https://github.com/influxdata/influxdb/blob/master/package.sh#L70

**Comment by jwilder** [comment]
Needs a `CHANGELOG` entry as well.

**Comment by corylanou** [comment]
There are several instances of `GOMAXPROCS` being set that can now be removed.  On master I see these lines:

```
$ Ack GOMAXPROCS

cmd/influx_tsm/main.go
70:     fs.BoolVar(&opts.Parallel, "parallel", false, "Perform parallel conversion. (up to GOMAXPROCS shards at once)")
161:            if !isEnvSet("GOMAXPROCS") {
162:                    // Only modify GOMAXPROCS if it wasn't set in the environment
163:                    // This means 'GOMAXPROCS=1 influx_tsm -parallel' will not actually
165:                    runtime.GOMAXPROCS(runtime.NumCPU())
183:    fmt.Printf("Parallel mode enabled (GOMAXPROCS): %s (%d)\n", yesno(opts.Parallel), runtime.GOMAXPROCS(0))

cmd/influx_tsm/README.md
51:Parallel mode enabled (GOMAXPROCS): yes (8)

cmd/influx_tsm/tracker.go
31:             pg:     NewParallelGroup(runtime.GOMAXPROCS(0)),

cmd/influxd/run/command.go
74:     runtime.GOMAXPROCS(runtime.NumCPU())
79:     log.Printf("Go version %s, GOMAXPROCS set to %d", runtime.Version(), runtime.GOMAXPROCS(0))

monitor/go_runtime.go
16:             "GOMAXPROCS": runtime.GOMAXPROCS(-1),
```

Monitor seems like we want that one (or someone put thought into that I guess).  Not sure about `influx_tsm`, but `influxd` should get changed.

**Comment by jwilder** [comment]
@corylanou `influx_tsm` one should stay as well.

**Comment by rossmcdonald** [comment]
`CHANGELOG` updated. 

@jwilder Regarding `package.sh`, that script is no longer used for any of our builds in lieu of `build.py`. I'm wondering if we should just remove it altogether?

**Comment by jwilder** [comment]
I'm not really familiar with it.  If you're positive it's not used anywhere then we should remove.

**Comment by jwilder** [comment]
👍 on green.

**Comment by rossmcdonald** [comment]
@jwilder Should we still remove the `GOMAXPROCS` references? Or should we just keep them there for now?

**Comment by jwilder** [comment]
@rossmcdonald Let's leave them there for now.

**Comment by rossmcdonald** [comment]
I've also updated the appveyor build to use Go 1.6, though I keep getting a failure in stress:
```
stress_test.go:417: Expected 0 to not be 0
```

**Comment by jwilder** [comment]
Maybe try:
```
diff --git a/stress/stress_test.go b/stress/stress_test.go
index 77e1ae5..a8e3b83 100644
--- a/stress/stress_test.go
+++ b/stress/stress_test.go
@@ -413,8 +413,8 @@ func TestBasicQueryClient_Query(t *testing.T) {
        }

        elapsed := r.Timer.Elapsed()
-       if elapsed == time.Duration(0) {
-               t.Errorf("Expected %v to not be 0", elapsed)
+       if elapsed.Nanoseconds() == 0 {
+               t.Errorf("Expected %v to not be 0", elapsed.Nanoseconds())
        }

 }
```

**Comment by e-dard** [comment]
LGTM 👍

**Comment by daviesalex** [comment]
Production machine change from 0.12 to 0.13 stable:

image

Every other metric pretty much unchanged. +1!

**Pull request merged**
