### PR TITLE
WIP for support selecting tag keys

### PR DESCRIPTION
**Pull request by jsternberg**
A potential solution for #4630. Allows the `@` sigil to be used to refer to a tag specifically.

### CODE REVIEW

**Comment by jsternberg** [comment]
@jwilder @mark-rushakoff a prototype if we decide on an alternative to #6410. This allows the following query to work:

```
SELECT value, host, @host FROM cpu
```

It will select both the field and the tag. The awkward part is that the columns conflict with each other and have to be implicitly renamed, but this isn't something we should encounter too often. This change brings the query language in line with treating tags and fields as fundamentally different. If we were at an earlier time (and maybe for 2.0), I would propose that we don't allow `host` to ever refer to a field and require `@host` to refer to a tag. We're not, so both syntaxes will have to be supported with `@host` referring specifically to a tag.

A possible benefit is we can detect a common error where people try to select only a tag. We can't currently detect that error since the query engine isn't sure if only tags are being referenced except when creating the cursors.

**Comment by pauldix** [comment]
There's still the issue of how to select all the fields. The problem is that `SELECT *` will also select the tags.

**Comment by jsternberg** [comment]
@pauldix should the wildcard only select fields or select fields and tags? The implementation in this PR will select both so this:

```
SELECT * FROM cpu
```

will expand to

```
SELECT host, @host, value FROM cpu
```

**Comment by pauldix** [comment]
@jsternberg took my discussion over to the big issue you opened :)

**Pull request closed without merging**
