### PR TITLE
docs: Fix typos in http/swagger.yml

### PR DESCRIPTION
**Pull request by pierwill**
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

**Review by 121watts — APPROVED** [review]

**Review by hoorayimhelping — APPROVED** [review]
better than most stuff on the internet these days

**Comment by pierwill** [comment]
Lol @hoorayimhelping thanks.

Can I merge this with the tests failing?

**Comment by pierwill** [comment]
Not sure how to diagnose the circleci e2e issue.

**Comment by hoorayimhelping** [comment]
@pierwill i'm seeing all greens, did you (or someone) rebuild? for posterity, that's probably the most expedient way to address e2e tests

**Comment by pierwill** [comment]
Looks like a fairy came by and fixed this. Thanks @hoorayimhelping, will do in the future. Merging!

**Pull request merged**
