### PR TITLE
Adding support for matching tags multiple times in Graphite parser

### PR DESCRIPTION
**Pull request by m4ce**
Original ticket #5416

### CODE REVIEW

**Comment by jwilder** [comment]
Graphite doesn't have a concept of a `host` so hard coding a special `host` tag doesn't make sense to me.  It seems like you want to be able to define a tag multiple times in a template and match/combine them?

**Comment by m4ce** [comment]
@jwilder,

well, the current use case I have only involve host, which is is easy since the separator should always be dot. But yes, the first thing that came to mind was to match tags multiple times, but then was separator to use?

Thanks,
Matteo

**Comment by jwilder** [comment]
@m4ce I understand.  The issue is that `host` is too specific for your use case for this plugin.  We'd have to generalize the PR to work with other tags for this to be able to be merged.

For separator, there is already a `separator` config option that should be used. By default, it's `.`.

**Comment by m4ce** [comment]
@jwilder,

I'm not a go developer, so I did what I could :) I hope the changes are good enough.

Thank you,
Matteo

**Comment by m4ce** [comment]
Any plan to merge this in the next release? Currently, I am deploying a custom binary around which is sub-optimal :)

**Comment by chrusty** [comment]
I've got a PR which is kinda related to this too:

https://github.com/influxdata/influxdb/pull/5562

**Comment by jwilder** [comment]
@m4ce This looks better.  We need to have some test cases for this code though.  You could add one fairly easily to this test case: https://github.com/influxdata/influxdb/blob/master/services/graphite/parser_test.go#L34

**Comment by m4ce** [comment]
@jwilder, I've added a case which tests multiple tags. I hope that is sufficient! Thank you!

**Comment by jwilder** [comment]
Thanks @m4ce

**Pull request merged**
