### PR TITLE
Ensure the backup directory exists.

### LINKED ISSUE #5350: 'influxd backup' should create backup directory
Hello,

it was somewhat surprising to find out that `influx backup` expects directory and not a filename. Actually, [docs](https://docs.influxdata.com/influxdb/v0.9/administration/backup_and_restore/) say `` Once you have your snapshot file''. Ok. Clearly, snapshot is created in given directory.

However, the following shouldn't either happen or be handled in better way, resp. check whether directory exists.

```
root@builder:~# influxd backup -host localhost:8086 /tmp/bar
2016/01/13 17:20:44 influxdb backup
2016/01/13 17:20:44 backing up metastore to /tmp/bar/meta.00
backup: open temp file: open /tmp/bar/meta.00.pending: no such file or directory
```

Thanks.

### PR DESCRIPTION
**Pull request by joelegasse**
Fixes #5350

### CODE REVIEW

**Comment by jwilder** [comment]
:+1: on green.

**Comment by dgnorton** [comment]
+1 on green and also update `CHANGELOG.md`

**Comment by jsternberg** [comment]
:+1: although is there any reasonable way to have the directory permissions go to whatever the default of `mkdir` would be? I don't know if there's anyway to do inherited directory permissions in Go, although I'm not sure it even matters.

**Comment by joelegasse** [comment]
@jsternberg: We probably don't want to "inherit" permissions from parent directories in the case that the only directory that exists is permissioned `rwx` for everyone. I looked for other instances of directory creation in the codebase, and saw that user-only was used most often (as opposed to user+group). That discussion would be better left as a more open topic, instead of here in this ticket.

In this case, the user creating the backup will most likely also be the user reading the backup files (either for restore or getting shipped off somewhere remotely), so I think user-only directory permissions should be fine.

**Pull request merged**
