### PR TITLE
Update CHANGELOG.md with release notes for 0.12.0

### PR DESCRIPTION
**Pull request by pauldix**
@toddboom

### CODE REVIEW

**Comment by toddboom** [comment]
:+1:

**Comment by e-dard** [comment]
LGTM 👍

**Comment by wonderflow** [comment]
`404 Not Found` when opening this url `https://docs.influxdata.com/influxdb/v0.12/administration/upgrading/`

**Comment by gunnaraasen** [comment]
@wonderflow the docs release was slightly behind this update. The link is live now.

**Comment by ashb** [comment]
So if this version no longer contains clustering code what's the option? the relay is broken by design because of cases like https://github.com/influxdata/influxdb-relay/issues/3#issuecomment-205598188.

Is there a paid option? None of the sales pages mention anything like it.

**Comment by filipskokorevs** [comment]
> Influx Enterprise and the clustering it offers will be deployed through our Influx Cloud offering before we offer it as an on premise binary. This will give us the ability to quickly iterate on the clustering offering and do multiple deployments a day in an environment that we have control over. For our cloud customers this means they’ll get the quickest fixes for any issues while our future on-premise customers will get a binary battle hardened through production use. 

> If you have comments, questions or concerns don’t hesitate to email me personally at paul@influxdb.com. We’re committed to the longevity of this project and having compelling free, open source software that we continue to improve.

**Pull request merged**
