### PR TITLE
fix(tsi): avoid concurrent delete

### LINKED ISSUE #14362: Panic due to concurrent map modification
I'm running the latest version of InfluxDB and stumbled into an application panic.

__Steps to reproduce:__
I currently can't reproduce the issue with certainty, it only happens from time to time when trying to run several delete queries at once.

__Expected behavior:__
No panic

__Actual behavior:__
A panic is thrown which results in an InfluxDB restart.

__Logs:__
2019-07-17T07:06:27.183380+02:00 metrics influxd: fatal error: concurrent map iteration and map write
2019-07-17T07:06:27.185441+02:00 metrics influxd: goroutine 152537573 [running]:
2019-07-17T07:06:27.185931+02:00 metrics influxd: runtime.throw(0x12f0502, 0x26)
2019-07-17T07:06:27.186208+02:00 metrics influxd: /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0000aebf8 sp=0xc0000aebc8 pc=0x42df92
2019-07-17T07:06:27.186483+02:00 metrics influxd: runtime.mapiternext(0xc0000aed38)
2019-07-17T07:06:27.186756+02:00 metrics influxd: /usr/local/go/src/runtime/map.go:790 +0x525 fp=0xc0000aec80 sp=0xc0000aebf8 pc=0x410945
2019-07-17T07:06:27.187068+02:00 metrics influxd: github.com/influxdata/influxdb/tsdb/index/tsi1.(*logTagKey).TagValueIterator(0xc0da8807f0, 0x0, 0x4)
2019-07-17T07:06:27.187335+02:00 metrics influxd: /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/log_file.go:1362 +0xf8 fp=0xc0000aeda8 sp=0xc0000aec80 pc=0xf13218
2019-07-17T07:06:27.187598+02:00 metrics influxd: github.com/influxdata/influxdb/tsdb/index/tsi1.tagKeyMergeElem.TagValueIterator(0xc1db5e8d20, 0x4, 0x5, 0x0, 0x0)
2019-07-17T07:06:27.187893+02:00 metrics influxd: /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/tsi1.go:271 +0xdb fp=0xc0000aee80 sp=0xc0000aeda8 pc=0xf2524b
2019-07-17T07:06:27.188166+02:00 metrics influxd: github.com/influxdata/influxdb/tsdb/index/tsi1.(*tagKeyMergeElem).TagValueIterator(0xc2454445c0, 0xc07d724240, 0x22)
2019-07-17T07:06:27.188424+02:00 metrics influxd: <autogenerated>:1 +0x4e fp=0xc0000aeeb8 sp=0xc0000aee80 pc=0xf2ad1e
2019-07-17T07:06:27.188672+02:00 metrics influxd: github.com/influxdata/influxdb/tsdb/index/tsi1.(*Partition).DropMeasurement(0xc057d2f200, 0xc07d724240, 0x22, 0x30, 0x0, 0x0)
2019-07-17T07:06:27.188963+02:00 metrics influxd: /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/partition.go:587 +0x18e fp=0xc0000aef60 sp=0xc0000aeeb8 pc=0xf1a2fe
2019-07-17T07:06:27.189339+02:00 metrics influxd: github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).DropMeasurement.func1(0xc079e8a854, 0xc0002f5950, 0xc1a9c41320, 0xc07d724240, 0x22, 0x30)
2019-07-17T07:06:27.189607+02:00 metrics influxd: /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:609 +0x4e fp=0xc0000aefb0 sp=0xc0000aef60 pc=0xf26bfe
2019-07-17T07:06:27.189920+02:00 metrics influxd: runtime.goexit()
2019-07-17T07:06:27.190249+02:00 metrics influxd: /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000aefb8 sp=0xc0000aefb0 pc=0x45d971
2019-07-17T07:06:27.190515+02:00 metrics influxd: created by github.com/influxdata/influxdb/tsdb/index/tsi1.(*Index).DropMeasurement
2019-07-17T07:06:27.190790+02:00 metrics influxd: /go/src/github.com/influxdata/influxdb/tsdb/index/tsi1/index.go:603 +0xf6

### PR DESCRIPTION
**Pull request by foobar**
The existing logic allows concurrent DELETEs run on a single shard, which may lead to panic due to concurrent access to the internal map of TSI index. This change makes DELETEs run serially.
Also for simplify, the epoch tracker is moved into the Shard struct.

Closes #14362

Describe your proposed changes here.

- [x] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by e-dard** [comment]
@foobar thanks for this! I need some time to review it.

**Comment by foobar** [comment]
@e-dard thanks! 
Just rebased to fix a conflict.

**Comment by foobar** [comment]
Hi @e-dard any update？

**Comment by e-dard** [comment]
@foobar thanks for this. I'm sorry I've only just been able to look at it. As I understand it, in #14362 it's possible to induce a panic due to concurrent r/w access to a map in the Logfile (in-memory) portion of a TSI access.

Your approach here is to serialise _all_ deletes on a shard. I'm concerned about this from a performance reason for a couple of reasons:

1) the default index in `1.7.x` is `inmem`, and this change is likely going to reduce performance of concurrent deletes when using that index, even though the change is to fix a defect in a different index type (TSI).
2) a delete works on two main structures the index and the TSM store itself (where the TSM files are).

I think it would be preferable to simply serialise access to the map in the TSI index only.

**Comment by foobar** [comment]
@e-dard thanks for looking into this. It makes sense to limit the change to TSI index because the problem only exists with TSI. That being said, I think the change may be more straight-forwarding. Please take a look at the updated change, which serialises the `DropMeasurement()` function.

**Comment by toomasp** [comment]
Well, I see no existing benchmarks among the tests for this code. Perhaps if @e-dard would specify exactly which parts of the code are performance sensitive and cover them with benchmarks it'd be easier to make a patch that would be accepted. Curiously, his own changes in the past have not been covered by benchmarks that demonstrate performance changes ( either good or bad ) - so I suppose as long as he's making the changes, it's okay.  

Best that can be done right now is a failing testcase for this issue so that it's reproducible. Then perhaps @e-dard will fix it, since his patches have been accepted.

**Comment by toomasp** [comment]
This seems to trigger it also, though via a slightly different path.

```go
package tsi1_test

import (
  "testing"
  "time"
)

func TestLogFile_ConcurrentDeleteTagValue(t *testing.T) {
  sfile := MustOpenSeriesFile()
  defer sfile.Close()
  lf, err := GenerateLogFile(sfile.SeriesFile, 1, 2, 1)
  if err != nil {
    t.Fatal(err)
  }
  timer := time.After(time.Second * 1)
  go func() {
    for {
      iter := lf.TagKeyIterator([]byte("measurement1"))
      if iter == nil {
        continue
      }
      for {
        e := iter.Next()
        if e == nil {
          break
        }
        kv := e.TagValueIterator()
        for {
          kvv := kv.Next()
          if kvv == nil {
            break
          }
        }
      }
    }
  }()
  go func() {
    for {
      _ = lf.DeleteTagValue([]byte("measurement1"), []byte("key1"), []byte("val2"))
    }
  }()
  <-timer
}
```

go test -race fails with:

```bash
==================
WARNING: DATA RACE
Write at 0x00c00013adb0 by goroutine 18:
  runtime.mapassign_faststr()
      C:/Go/src/runtime/map_faststr.go:202 +0x0
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execDeleteTagValueEntry()
      C:/Users/toomasp/IdeaProjects/influxdb/tsdb/index/tsi1/log_file.go:660 +0x4eb
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).execEntry()
      C:/Users/toomasp/IdeaProjects/influxdb/tsdb/index/tsi1/log_file.go:630 +0x89
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*LogFile).DeleteTagValue()

....

Previous read at 0x00c0001f8508 by goroutine 17:
  github.com/influxdata/influxdb/tsdb/index/tsi1.(*logTagKey).TagValueIterator()
      C:/Users/toomasp/IdeaProjects/influxdb/tsdb/index/tsi1/log_file.go:1362 +0x19e
```

**Comment by foobar** [comment]
> This seems to trigger it also, though via a slightly different path.
@toomasp just wondering, would you push this test case ?

**Comment by dgnorton** [comment]
@foobar As @e-dard mentioned, this is a real bug that needs to be fixed but it's probably too expensive to lock the whole index. Do you want to continue working on this issue? If so, we'll leave the PR open. It'll need a benchmark added and locking at a finer grained level. If you'd rather not work on it, we'll close this PR and add the issue to our backlog and schedule it to be fixed. Thanks for your help on this issue and others.

**Comment by foobar** [comment]
@dgnorton I'd work on it. 
But given that the bug is tracked with #14362, I suppose it's ok to close this pr?

**Comment by dgnorton** [comment]
@foobar Okay, I'll close this PR. If you start work on a finer grained locking approach, can you add a benchmark so we can compare before & after? Also, if you have an idea for finer grained locking and want to discuss on the issue before implementing, we'd be glad to help and make sure the change will be something we can merge. Thanks again for your patience and contributions.

**Pull request closed without merging**
