### PR TITLE
Changelog for 0.12.2

### PR DESCRIPTION
**Pull request by kostasb**
###### Required for all non-trivial PRs
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [ ] [InfluxQL Spec](https://github.com/influxdata/influxdb/blob/master/influxql/README.md) updated

Updated Changelog with details for 0.12.2

### CODE REVIEW

**Comment by e-dard** [comment]
LGTM 👍

**Comment by jsternberg** [comment]
Can you remove duplicates from the 0.13 section?

**Comment by kostasb** [comment]
Duplicates removed from v0.13.

**Comment by jwilder** [comment]
👍

**Pull request merged**
