### PR TITLE
fix determine the file size

### PR DESCRIPTION
**Pull request by runner-mei**
fix determine the file size

### CODE REVIEW

**Comment by jwilder** [comment]
@runner-mei Can you rebase?

**Comment by runner-mei** [comment]
I rebase it.

**Comment by corylanou** [comment]
+1.  /cc @jwilder

**Comment by corylanou** [comment]
@runner-mei We are waiting for the `0.10` release branch to finalize before merging your PR's.  Thank you for your patience and great contributions!

**Comment by jwilder** [comment]
Thanks @runner-mei!

**Pull request merged**
