### PR TITLE
version should be 0.10 rather than 0.9

### PR DESCRIPTION
**Pull request by CrazyJvm**
wrong version make us confusing when we test 0.10

### CODE REVIEW

**Comment by zstyblik** [comment]
@CrazyJvm despite you have a good point, I don't think master branch is v0.10. v0.10 lives in v0.10 branch.

**Comment by CrazyJvm** [comment]
Please feel free to close it if you think it's unnecessary.

**Comment by mark-rushakoff** [comment]
@zstyblik is correct – master is currently developing towards 0.11.

You should only see `0.9` displayed if you're running a local build and you [haven't specified ldflags](https://github.com/influxdata/influxdb/blob/710f32321a0224c8ac5c759e61ad303d02274551/package.sh#L277).

**Comment by zstyblik** [comment]
@mark-rushakoff if I understand it correctly, all version branches "fork" off from master, correct? Since 'version' is string, it might make sense to put something like 'master' as a version and replace it every time new version branch is forked off or through build flags rather than pushing it now and then, resp. forgetting to do so. Also, 'master' is a bleeding edge and not specific version.

**Pull request closed without merging**
