### PR TITLE
fix(endpoint): when looking up a endpoint we should allow org only lookup

### PR DESCRIPTION
**Pull request by lyondhill**
In the current system the api always adds "UserID" to the filter. This only
allows the system to look up endpoints that user created. The behavior should be
that we filter based on user input and use authorizer to hide things they shouldn't see.

### CODE REVIEW

**Comment by kelwang** [comment]
As the current implementation Authorizer is the last step filter to get all responses. We used to seen an issue, if user make a request /API/v2/endpoints, if the server has for example 2000 endpoints, it will pull like  the first 100 points of all orgs. Then filter by authorizer, so we will very likely see less endpoints, if the user don't have the org parameter. If we want to get rid of this requirement, we have to make the org parameter required or extract the org from the authorizer which is not possible yet, since the session auth has no org id.

**Comment by desa** [comment]
@kelwang 
>  if the server has for example 2000 endpoints, it will pull like the first 100 points of all orgs. 
That sounds like there's a bug in the authorizer then.

**Comment by lyondhill** [comment]
So we would need a temporary solution that ensure's the userID or the org is present? That is until the bug that @desa identified can be resolved?

**Comment by lyondhill** [comment]
the Other option is to error in the auth if you attempt to lookup the entire collection. (ie no filter)

**Comment by desa** [comment]
@kelwang I actually don't understand why this wont fix the issue that @lyondhill is seeing.

**Comment by lyondhill** [comment]
It does fix my issue (tested on oss) but if someone where to hi the api with no filter then the results that are not authorized are filtered from the list. Add in pagination and the user may get a list of 0 if enough org's exist that the user doesn't have access to.

The solution to that problem is either :
1 - reject any "unfiltered" lookups to the colection
2 - Force a user filter if they dont specify any filters.

@desa which of these (or any additional options) would you like to see?

**Comment by desa** [comment]
@lyondhill Thanks for clarifying that. That makes a lot of sense now. It sounds like there's a bug in pagination. I'd like to see pagination implemented correctly. That would solve the issue correct?

**Comment by lyondhill** [comment]
if pagination happened after authorization then yes. It would be a pretty big refactor to the way its being done now. I believe this pagination problem would exist for most the other collections in our system. The problem is that pagination happens on the database layer and for all list's the auth happens as a wrapper around the db using the `/authorizer` package.

**Pull request merged**
