### PR TITLE
Create man pages for commands

### LINKED ISSUE #7011: Create man pages for commands and various other information
### Feature Request

Create man pages for commands and the various other information that would be useful to developers for offline and quick access.

Developers, myself especially, like being able to access information on how to use a command with man. We expect it out of our tools even if we never use it. We should try to generate man page documentation that can be deployed with the various influx packages.

__Proposal:__ Create man pages (probably using something like asciidoc)

__Current behavior:__ No documentation using man.

__Desired behavior:__ `man influxd` or `man influx` shows what the commands do. `man influxql` describes the query language.

__Use case:__ Developers love it. It may also help improve our own development time as we will be able to access documentation offline more easily and command line developers commonly know how to search through man pages faster than web pages.

Credit to @corylanou who came up with the idea.

### PR DESCRIPTION
**Pull request by jsternberg**
Fixes #7011.

### CODE REVIEW

**Comment by jsternberg** [comment]
Some initial work for providing man pages. There's still a lot more we can write that would be good like `influxql` and other operational information, but I think this is a good initial start. I also haven't written man pages for `influx_stress`, `influx_inspect`, or `influx_tsm` yet.

@corylanou @jwilder @beckettsean

**Comment by corylanou** [comment]
This looks like a great start.  I don't know how man pages are installed, so I'll trust that is all correct.  This will be a great starting point to have the community add in more information.  We should create a `help wanted` issue once this is merged that asks for more man page contributions.  +1

**Comment by jwilder** [comment]
@rossmcdonald Can you take a look?

**Comment by gunnaraasen** [comment]
Maybe add a line to the [GitHub pull request template](https://github.com/influxdata/influxdb/blob/master/.github/PULL_REQUEST_TEMPLATE.md) reminding people to update the man pages if they alter command line usage for any of the `influx*` binaries.

**Comment by rossmcdonald** [comment]
👍  This looks good. I tested on CentOS 7 and Ubuntu Trusty and Xenial without issue.

**Pull request merged**
