### PR TITLE
feat(clientLibs): add Kotlin and Scala client library

### PR DESCRIPTION
**Pull request by bednar**
1. add Kotlin client library
1. add Scala client library

`KotlinLogo.tsx` and `ScalaLogo.tsx` are just placeholders.

Screenshot 2020-05-22 at 09 09 55

Screenshot 2020-05-22 at 09 10 25
Screenshot 2020-05-22 at 09 10 11

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by timhallinflux** [comment]
@russorat -- needs some icons. :-)

**Comment by bednar** [comment]
I just added an icon for Kotlin:

Screenshot 2020-05-25 at 14 18 23

**Comment by alexpaxton** [comment]
If the icons have gradients they aren't going to display properly in Safari. We had to update all the other icons to be "flat" aka no gradients.

Also, I'd add some whitespace around those SVGs so they don't seem so huge compared to the others

**Comment by bednar** [comment]
@alexpaxton thanks for response.

Could you send me a proper icon? Also I gave you permission to https://github.com/bednar/influxdb if you would like to change it in sources - https://github.com/bednar/influxdb/tree/docs/client-jvm-libraries.

**Comment by russorat** [comment]
Pushed an update to the icons. Verified they work in safari and chrome.

image (52)

**Pull request merged**
