### PR TITLE
update PR template to avoid stale InfluxQL spec

### PR DESCRIPTION
**Pull request by beckettsean**
- [x] Rebased/mergable
- [x] Tests pass

### CODE REVIEW

**Comment by beckettsean** [comment]
@jwilder, this is done because we're seeing a lot of docs repo issues about the InfluxQL spec being out of sync. The one in the repo should be the single source of truth. It would be best if devs update on feature merge rather than support updating when the feature is finally documented or someone in the community notices.

**Comment by beckettsean** [comment]
@rkuchan

**Comment by gunnaraasen** [comment]
+1 to adding this. I also like how Homebrew structures their [PR template](https://github.com/Homebrew/homebrew/blob/master/.github/PULL_REQUEST_TEMPLATE.md) with "_You can erase any parts of this template not applicable to your Pull Request._".

**Comment by jwilder** [comment]
:+1:

**Comment by beckettsean** [comment]
@gunnaraasen @jwilder I made some changes with Gunnar's feedback in mind. Can you quickly review?

**Comment by gunnaraasen** [comment]
:+1:

**Comment by jwilder** [comment]
:+1:

**Pull request merged**
