### PR TITLE
Don't force root path on admin.js getClientVersion()

### PR DESCRIPTION
**Pull request by keras**
Similar to #1339.

Fix getClientVersion() on setups where the admin interface resides on some other path than root path due to some reverse proxy setup.

### CODE REVIEW

**Comment by toddboom** [comment]
@keras Thanks for submitting this! Could you sign the CLA?
https://influxdb.com/community/cla.html

Also, if you could rebuild the assets, that will save us a step after merging:
https://github.com/influxdata/influxdb/tree/master/services/admin

**Comment by keras** [comment]
Done.

**Comment by e-dard** [comment]
@keras This needs a rebase. Once that's done I can merge it for you. 👍

**Comment by keras** [comment]
@e-dard: Sorry I've been bit busy and forgot this. But now it's rebased.

**Comment by e-dard** [comment]
Thanks @keras!

**Pull request merged**
