### PR TITLE
refactor: Move Catalog into influxdb3_catalog crate

### LINKED ISSUE #25204: Refactor Catalog into its own crate
The Catalog now has more data than just the schema, some of which will need to be serialized into the WAL. In order to update the WAL to store other kinds of catalog updates (like the addition or deletion of a last value cache), the WAL will need to reference the Catalog.

Follow on work for #25196 

Pre-requisite for #25203

### PR DESCRIPTION
**Pull request by pauldix**
This moves the catalog and its serialization logic into its own crate. This is a precursor to recording more catalog modifications into the WAL.

Closes #25204

### CODE REVIEW

**Review by mgattozzi — APPROVED** [review]

**Comment by mgattozzi** [comment]
You'll just need to handle key deprecations with cargo-deny -> https://github.com/EmbarkStudios/cargo-deny/pull/611

You'll need to update your copy of `cargo-deny` to make sure it works when you fix it

**Comment by pauldix** [comment]
@mgattozzi so what do I need to do for this? Just cargo update?

**Comment by mgattozzi** [comment]
The deny.toml file itself needs updating to the V2 version. There should be more instructions in the issue I linked

**Comment by pauldix** [comment]
Hmmm that issue is not all clear to me. I don't know what it means or what I should do. It claims it "provides a way", but I don't see what that way might be. It talks about Version 2, but I don't know what that is as here's what I have and I think I have an up to date toolchain and just ran cargo update:

```
> cargo deny -V
cargo-deny 0.14.15
```

Basically, I have no clue what I should be doing here. Changing something about our CI? Changing something about the `deny.toml` file in our repo? Running some command?

**Comment by pauldix** [comment]
Spent more time reading through that issue. I guess maybe adding a `version = 2` to the two sections in the deny.toml file will do the trick, but not sure. Will see after CI run for 0cc567fe78364c83d82fee344510fff7108734af

**Comment by pauldix** [comment]
Gah, that didn't do it. Unfortunately, I'm unable to reproduce the errors that CI is having with this.

**Comment by pauldix** [comment]
Ok, I removed the deprecated deny fields, but ended up having to set allows on the license section since the new default was to deny everything. Would appreciate a review of that real quick: fef816778e5da043da003ee80a0087066e36e374

Also worth @jdstrand taking a look at that config to confirm it's ok.

**Comment by pauldix** [comment]
Going to merge this in as it's passing all checks now. I assume the `deny` changes are ok as the licenses there are all permissive. If there are any problems, I'll address in a follow on PR.

**Comment by jdstrand** [comment]
> Ok, I removed the deprecated deny fields, but ended up having to set allows on the license section since the new default was to deny everything. Would appreciate a review of that real quick: [fef8167](https://github.com/influxdata/influxdb/commit/fef816778e5da043da003ee80a0087066e36e374)
> 
> Also worth @jdstrand taking a look at that config to confirm it's ok.

Reading https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html, this all looks good to me. cc @tarainfluxd

**Pull request merged**
