### PR TITLE
Incorrect variable referenced (`todo_lines` should be `fixme_lines`)

### PR DESCRIPTION
**Pull request by swarbiv**

### CODE REVIEW

**Comment by corylanou** [comment]
Makes sense.  +1

**Comment by zstyblik** [comment]
Is a review-pair really necessary for a such change?

**Comment by jwilder** [comment]
@swarbiv Can you sign the CLA? https://influxdb.com/community/cla.html

**Comment by e-dard** [comment]
@swarbiv we're happy to accept this PR but you have to sign the [CLA here](https://influxdb.com/community/cla.html).

**Comment by toddboom** [comment]
@swarbiv If you can get the CLA signed this week, we can merged this in, otherwise we'll need to close out this PR. Thanks!

**Comment by toddboom** [comment]
We can't merge this without the CLA, so I'm closing this out.

**Pull request closed without merging**
