### PR TITLE
Merge should work with a regex

### PR DESCRIPTION
**Pull request by jvshahid**
Like this example

``` sql
select * from merge(/stats.*/)
```

### CODE REVIEW

**Comment by yee379** [comment]
i'm not sure this is related, but i can't get the merge to work:

    $ curl -G 'http://localhost:8086/db/ptolemy/series?u=root&p=root' --data-urlencode "q=list series /com.blah.ap-b050.*.user_stats.neighbour.\d+/"
    [{"name":"list_series_result","columns":["time","name"],"points":[[0,"com.blah.ap-b050-roof-ne.user_stats.neighbour.0"],[0,"com.blah.ap-b050-roof-ne.user_stats.neighbour.1"],[0,"com.blah.ap-b050f2-2ar29.user_stats.neighbour.0"],[0,"com.blah.ap-b050f2-2ar29.user_stats.neighbour.1"],[0,"com.blah.ap-b050r100.user_stats.neighbour.0"],[0,"com.blah.ap-b050r100.user_stats.neighbour.1"],[0,"com.blah.ap-b050r113.user_stats.neighbour.0"],[0,"com.blah.ap-b050r113.user_stats.neighbour.1"],[0,"com.blah.ap-b050r318.user_stats.neighbour.0"],[0,"com.blah.ap-b050r318.user_stats.neighbour.1"],[0,"com.blah.ap-b050r347.user_stats.neighbour.0"],[0,"com.blah.ap-b050r347.user_stats.neighbour.1"],[0,"com.blah.ap-b050r362-test2.user_stats.neighbour.0"],[0,"com.blah.ap-b050r362-test2.user_stats.neighbour.1"],[0,"com.blah.ap-b050r362-test2.user_stats.neighbour.2"],[0,"com.blah.ap-b050r367.user_stats.neighbour.0"],[0,"com.blah.ap-b050r367.user_stats.neighbour.1"],[0,"com.blah.ap-b050r375.user_stats.neighbour.0"],[0,"com.blah.ap-b050r375.user_stats.neighbour.1"],[0,"com.blah.ap-b050s.user_stats.neighbour.0"],[0,"com.blah.ap-b050s.user_stats.neighbour.1"]]}]

so the regex is okay... but then i try:

    curl -G 'http://localhost:8086/db/ptolemy/series?u=root&p=root' --data-urlencode "q=select number from merge(/com.blah.ap-b050.*.user_stats.neighbour.\d+/)"
    Cannot find user root

**Comment by genofire** [comment]
Me too :(
What i am doing wrong?

```
/query?db=test&epoch=ms&p=[REDACTED]&q=SELECT+sum("value")+FROM+MERGE/httpjson_nodes_.*_statistics_clients/
```
Result:
```
{"error":"error parsing query: found /, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 31"}
```

---

```
/query?db=test&epoch=ms&p=[REDACTED]&q=SELECT+sum("value")+FROM+MERGE(/httpjson_nodes_.*_statistics_clients/)
```
Result:
```
{"error":"error parsing query: found (, expected regex at line 1, char 31"}
```

**Comment by beckettsean** [comment]
@genofire your comment is on a PR that hasn't been updated in a year. Please open a new issue with all your relevant details so this PR can rest in peace.

**Comment by bechampion** [comment]
Im on nighly build and merge don't seem to work... as im collecting network stats it'd be nice to display a grafana text with the total SUM() of all the series ,  i hope this comes in soon

**Comment by genofire** [comment]
@bechampion check out the version and documentation to this version.
(The team of influxdb does not write explicit down, which features are not supported any more - influxdb is not backward compatible :( )

PS: this branch was merged, it mean that in version 0.8.4 this function are implemented.

**Pull request merged**
