### PR TITLE
docs(http): update request body for updating a task

### LINKED ISSUE #12027: Swagger doc: Update Task: make orgid/orgname readOnly.
The following elements are not readOnly in swagger.doc for Update Task endpoint:
- `orgID`
- `org`
- `links`
- `authorizationID`
The above elements need to be `readOnly`

Also I am seeing `owner` is being part of a swagger.doc, but owner and member links returned in the `link`. Should it be removed?

### PR DESCRIPTION
**Pull request by zhulongcheng**
Closes #12027

_Briefly describe your proposed changes:_

  - [x] Rebased/mergeable
  - [ ] Tests pass
  - [x] http/swagger.yml updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by zhulongcheng** [comment]
Hi @mark-rushakoff  , request a review.

**Comment by mark-rushakoff** [comment]
Good catches @zhulongcheng, thanks. Merging with red litmus_daily as known issue #11965.

**Comment by gshif** [comment]
@mark-rushakoff , two fields are required : `flux` and `name`, I am going to have a separate PR to add required: [flux, name]

**Comment by mark-rushakoff** [comment]
@gshif neither of those are supposed to be required.  It's supposed to be at least one of the properties on TaskUpdate. It's fine if it's only `token` or only `status` or only `flux` or only `name`.

**Pull request merged**
