### PR TITLE
mutex lock around measurement field map access

### PR DESCRIPTION
**Pull request by arussellsaw**
fix for https://github.com/influxdata/influxdb/issues/6720
CLA is signed

### CODE REVIEW

**Comment by benbjohnson** [comment]
This seems like it would work although it might make more sense to simply lock around the entire `LoadMetadataIndex()`. It seems like the whole shard should be locked while loading. @jwilder?

**Comment by e-dard** [comment]
@arussellsaw instead of wrapping the code with a `Lock`, you can get rid of that stuff and just do:

```go
mf  := e.MeasurementFields(measurement)
```

@jwilder FYI this PR is the other fix that I put into https://github.com/influxdata/influxdb/pull/6647 but you suggested it was not needed, so I took it out 😄.  If you're sure it should only be getting called from one goroutine, possibly there is another bug lurking somewhere?

**Comment by benbjohnson** [comment]
@e-dard I agree with @jwilder that it doesn't seem like this _should_ be necessary. The engine shouldn't be building cursors before the shard has been loaded.

**Comment by jwilder** [comment]
It looks like this panic is happening because the check for whether a shard is closed is `s.engine == nil`.  When the shard is opened, it creates an engine and assigns it to `s.engine` on [L167](https://github.com/influxdata/influxdb/blob/master/tsdb/shard.go#L167) _before_ it calls `LoadMetadataIndex`.  That assignment causes `isClosed` to return true before the engine is actually ready which allows queries and writes to occur on the shard.

I think L167 needs to be moved down to maybe L187 and then the read lock should not be needed in `LoadMetadataIndex`.

**Comment by arussellsaw** [comment]
updated, let me know if you guys would rather take over though. as i'm not familiar with the engine internals

**Comment by e-dard** [comment]
LGTM 👍  Thanks, Alex.

**Pull request merged**
