### PR TITLE
Fixing misspelt heading in configuration example

### PR DESCRIPTION
**Pull request by andyfeller**
Minor change fixing sample configuration file whose header was misspelt.  Code correctly references toml:subscriber so no functional impact

### CODE REVIEW

**Comment by gunnaraasen** [comment]
LGTM

**Comment by e-dard** [comment]
@andyfeller can you sign the [CLA](https://influxdata.com/community/cla/) please?

**Comment by andyfeller** [comment]
@e-dard done

**Comment by e-dard** [comment]
@andyfeller do you possibly need to rebase from latest master? Not sure what's going on with your commit history there.

**Comment by andyfeller** [comment]
I think this is due to be rebasing with upstream/master.  Going to see about clearing this up.

**Pull request closed without merging**
