### PR TITLE
influx_tsm bugfixes in 0.10.0

### PR DESCRIPTION
**Pull request by joelegasse**
These changes were already made to the 0.10 branch, and should be included

### CODE REVIEW

**Comment by jwilder** [comment]
:+1:

**Comment by jonseymour** [comment]
@joelegasse I disagree that the changes were a mess from a git perspective. I am willing to explain why not, if you like. However, thank you.

**Comment by joelegasse** [comment]
I misread your comment, then. I thought you were suggesting they weren't
cleanly integrated in to master, and that's why you submitted a separate
pull request. But looking at the timing, I just missed your PR when I
created mine...

**Comment by jonseymour** [comment]
No problem. The original change that was there before #5704 was intended to resolve the conflict in 0.10.0 based on my misunderstanding that 0.10.0 would eventually be merged into master. Jason explained that this isn't what normally happens. I created #5709 which merged the changes back into master without knowing that you had rebased/cherry-picked the changes onto another branch and merged them that way.

All good - thanks for getting them in there.

**Pull request merged**
