### PR TITLE
Merge branch '1.0'

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by jsternberg** [comment]
I'm going to wait for this to become green for tests and get reviewed, then I'm going to close this and push directly to master to avoid two merge commits.

@jwilder can you take a look at this?

**Comment by jwilder** [comment]
```
# github.com/influxdata/influxdb/services/httpd
services/httpd/response_writer.go:29: undefined: csvResponseWriter
```

**Comment by jsternberg** [comment]
Fixed.

**Comment by jwilder** [comment]
👍

**Pull request merged**
