### PR TITLE
Backport 7832 & 7929 & 8011

### PR DESCRIPTION
**Pull request by gunnaraasen**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by jwilder** [comment]
Also need this one: https://github.com/influxdata/influxdb/pull/7929

**Comment by gunnaraasen** [comment]
Ok, I'll add that one as well.

**Comment by jwilder** [comment]
```
# github.com/influxdata/influxdb/tsdb
tsdb/meta.go:1616: s.Tags.Clone undefined (type models.Tags has no field or method Clone)
```

Looks like `Tags.Clone` doesn't exist in `1.1` branch.

**Comment by rossmcdonald** [comment]
Looks like we need this pulled in as well for `Tags.Clone`: https://github.com/influxdata/influxdb/pull/7832

**Pull request merged**
