### PR TITLE
fix(ui): remove lodash _ all

### LINKED ISSUE #15694: Eradicate `import _ from 'lodash'` in favor of importing individual functions
our lodash footprint is ginormous.

### PR DESCRIPTION
**Pull request by zoesteinkamp**
clean up complete

Closes #15694 

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by Asalem1** [comment]
I wonder if we should incorporate this eslint-plugin so enforce these import changes so that future developers don't undo all this hard work:

https://github.com/wix/eslint-plugin-lodash

**Comment by zoesteinkamp** [comment]
This issue is going on hold for now, to be addressed at a later time when we have the ability to solve some of its issues.

**Comment by russorat** [comment]
@zoesteinkamp should we close this?

**Comment by wbaker85** [comment]
Since we are now using the UI assets from the `ui` repository (#21090), I am closing this PR!

**Pull request closed without merging**
