### PR TITLE
Remove redundant error return of (Client) Database(name string)

### PR DESCRIPTION
**Pull request by seiflotfy**

### CODE REVIEW

**Comment by corylanou** [comment]
Addresses first part of #5516.

Can you update the changelog to reference that you fixed the first part of that issue as well.

Sanitized code, so refreshing!  +1

**Comment by seiflotfy** [comment]
Changelog updated

**Comment by seiflotfy** [comment]
Had to rebase again on top of new master

**Comment by corylanou** [comment]
Looks like we need yet another rebase.  We moved a lot of code today :-).

**Comment by seiflotfy** [comment]
no worries. rebased :D

**Comment by seiflotfy** [comment]
@corylanou @benbjohnson do you want me to revisit this?

**Comment by seiflotfy** [comment]
@toddboom done

**Comment by toddboom** [comment]
this got a verbal :+1: from @e-dard and @jwilder, merging.

**Pull request merged**
