### PR TITLE
added a button to generate permalink to queries entered in admin UI.

### LINKED ISSUE #4987: Permalinks to queries in Web Admin
Sometimes I need to send colleagues samples of queries I make in Web Admin interface.
At the moment there is no way to send such URLs.
It would be cool, if Web Admin supports permalinks like
`http://db:8083/query?q=SHOW+FIELD+KEYS&db=test`

### PR DESCRIPTION
**Pull request by Vidhuran**
Fixes #4987

influxdb

### CODE REVIEW

**Comment by Vidhuran** [comment]
- [✓] CHANGELOG.md updated
- [✓] Rebased/mergable
- [✓] Tests pass
- [✓] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

**Comment by toddboom** [comment]
@Vidhuran I like this idea, though I think it doesn't quite address what was asked for in #4987. I think that issue wanted a way to have permalinks open up the Admin UI directly.

I still think this is a good addition, though I've got one small request. Can we change "Generate permalink" to "Generate Query URL" and the content inside the modal to "URL for the Query".

If you can do that and rebase it, I'll get it merged for v0.13.0. Thanks!

**Comment by Vidhuran** [comment]
Ah, Ok , I see the difference , i will make the changes that you had suggested for this PR and then make a new PR to fix the original problem.

**Comment by toddboom** [comment]
@Vidhuran Awesome, thanks!

**Pull request merged**
