### PR TITLE
Add difference

### PR DESCRIPTION
**Pull request by sjeandeaux**
* Parsing select with aggregate method `diff`
* Map Reduce => Diff 

- [X] CHANGELOG.md updated
- [X] Rebased/mergable
- [ ] Tests pass
- [X] Sign [CLA](http://influxdb.com/community/cla.html) (if not already signed)

### CODE REVIEW

**Comment by sjeandeaux** [comment]
Sorry, I have a question. 
On my own circleci, the build fails. I delete it and it's OK on influxdb's circleci.
Do we need to have specific configuration for circleci?

Message when it fails `Failed to destroy btrfs snapshot: operation not permitted`

**Comment by jwilder** [comment]
#5196 has significantly changed how the query engine works.  This PR needs to be updated based on those changes.

**Comment by jsternberg** [comment]
The difference aggregate should probably work similarly to `derivative()`, but this PR has it working more similar to the selectors like `last()`. Since this PR isn't currently mergeable, I'm going to close the PR. Feel free to rebase and modify the PR and reopen if you have time to update this and I'll take another look.

Thanks!

**Comment by arapov** [comment]
@sjeandeaux, do you plan to rebase it or lost an interest?

**Comment by sjeandeaux** [comment]
i rebase, i work on. i need to integrate the changes.

**Comment by arapov** [comment]
@sjeandeaux and when do you think you could do it, I will be happy to test it.

**Pull request closed without merging**
