### PR TITLE
Support wildcards in aggregate functions

### LINKED ISSUE #5750: Wildcard support for fields in continuous queries.
when the only value was "value", there was a simple way to create a dynamic CQ when backreferencing `:measurement` however the new format telegraf uses seems to break this.

https://docs.influxdata.com/influxdb/v0.10/query_language/continuous_queries/#cqs-with-backreferencing

I'm wondering if there is a better way to do this so sub measurements are included.
```
CREATE DATABASE telegraf WITH DURATION 100d
CREATE RETENTION POLICY "7y" ON telegraf DURATION 2555d REPLICATION 1

CREATE CONTINUOUS QUERY "30m_cpu" ON telegraf BEGIN SELECT mean(usage_idle) as usage_idle INTO telegraf."7y".:measurement FROM telegraf."default".cpu GROUP BY time(30m), host END

CREATE CONTINUOUS QUERY "30m_mem" ON telegraf BEGIN SELECT mean(used_percent) as used_percent INTO telegraf."7y".:measurement FROM telegraf."default".mem GROUP BY time(30m), host END

CREATE CONTINUOUS QUERY "30m_disk" ON telegraf BEGIN SELECT mean(used_percent) as used_percent INTO telegraf."7y".:measurement FROM telegraf."default".disk GROUP BY time(30m), host END
```

### PR DESCRIPTION
**Pull request by jsternberg**
Fixes #5750.

### CODE REVIEW

**Comment by beckettsean** [comment]
@jsternberg one common use case will be to downsample in bulk. E.g. 

`SELECT MEAN(*) INTO foo FROM bar GROUP BY time(5m)`.

Let's assume that `bar` has field keys `int`, `float`, `bool`, and `string` with types to match. 

Two questions:
1. What field keys would be persisted in `foo`? `mean_int`? `int_mean`? `mean_1`?
2. What happens for `bool` and `string`, which are invalid types for `MEAN()`? Does the whole query error out? Does the system just ignore fields with mismatched types?

Also, I noticed you don't use `boolean` as a type in any of the tests. It's an uncommon type but should be tested as much as the others so we don't end up with edge cases.

**Comment by jsternberg** [comment]
I'll add a test for it. I'm just letting my laziness catch up with me since I didn't want to add another one, but you're right it's important. Questions in order:

1. Field keys will be persisted as a combination of the original alias combined with the name of the field. So `mean(*)` with `value` as one of the fields will expand to `mean(value::float) AS mean_value`. I thought this was the best way to deal with it. You can also customize this with `mean(*) AS wildcard` to expand to `mean(value::float) AS wildcard_value`. I should add a test for that though.
2. Types that are invalid for the function will be discarded so `mean(*)` will _only_ select values that are floats or integers. I tried my best to get these rights, but please report bugs of anything I missed. By default, everything can accept floats and integers so those should always work. I have to manually OK a function so that it supports strings or booleans.

**Comment by beckettsean** [comment]
That all sounds great, @jsternberg, thanks! It's the behavior I would expect without knowing anything else, and I don't see any issues with it. Guaranteed we will have customers who want `mean(*) as foo` to end up with `<field_key>_foo` as the new field key name, so if we can support that, awesome.

**Comment by jsternberg** [comment]
I don't really know what syntax we would use to support that. If you have any ideas, I'll implement it. I had to make a decision of something to name it though.

**Comment by beckettsean** [comment]
@jsternberg I don't understand why the `AS` syntax won't work as described. We just note that when used with `(*)` it's a suffix to be added to the existing field key, rather than the complete field key.

@rkuchan @gunnaraasen thoughts?

**Comment by jsternberg** [comment]
I'm not sure I understand. The alias has to either be the prefix or the suffix. Right now, it's the prefix. Should it always be the suffix? The difficult part is letting the user choose which one they want. I thought having the alias a prefix made the most sense personally.

**Comment by beckettsean** [comment]
@jsternberg in re-reading your examples I see what you mean that you had it as a prefix. That's probably better. I would rather `bool`, `float`, `int`, `string` `AS foo` become

```
foo_bool
foo_float
foo_int
foo_string
```
than
```
bool_foo
float_foo
int_foo
string_foo
```

**Comment by beckettsean** [comment]
I see no reason to let the user choose. Make it always a prefix.

**Comment by gunnaraasen** [comment]
I like the idea of forcing to a prefix when using `AS` with a wildcard aggregate on the first pass. People can enumerate fields if they want anything more complicated.

In the future, we could add something like the [CQ back reference](https://docs.influxdata.com/influxdb/v0.13/query_language/continuous_queries/#cqs-with-backreferencing).

**Comment by rpk113** [comment]
Just to clarify..  would this work?

 SELECT MEAN(*::field) AS *::field INTO foo FROM bar GROUP BY time(5m)?

**Comment by jsternberg** [comment]
You don't need the `AS`, but the rest is fine and would work.

**Comment by rpk113** [comment]
if I wanted to keep the measurement name the same within down sampled retention policies would the AS be correct?

**Comment by jsternberg** [comment]
I don't think it's possible at the moment to keep the field name the same with wildcards.

**Comment by kerams** [comment]
@jsternberg What would it take to make that possible? Neither TICK scripts nor InfluxQL support support keeping field names the same when downsampling with wildcards. It's really annoying that you cannot reuse queries and just plug in different retention policies.

**Comment by steverweber** [comment]
https://github.com/influxdata/influxdb/issues/7332

**Comment by nagimov** [comment]
@jsternberg Any chance you guys can take another look at this? This is IMO a very foundational functionality for a time-series database. Downsampling of all the fields in the measurement is a very common scenario. It currently requires corresponding CQs to be updated every time a new field is introduced and it doesn't feel to be the right way for a "schemaless database".

**Pull request merged**
