### PR TITLE
Make magacheck bot great again

### PR DESCRIPTION
**Pull request by e-dard**
Testing some changes to the megacheck bot.

### CODE REVIEW

**Comment by e-dard** [comment]
this should not get deleted.

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
```/tmp/742608305/src/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:111:28: InternalMessageInfo not declared by package proto
couldn't load packages due to errors: google.golang.org/genproto/googleapis/rpc/status
```

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
```/tmp/615729525/src/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:111:28: InternalMessageInfo not declared by package proto
couldn't load packages due to errors: google.golang.org/genproto/googleapis/rpc/status
```

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
```/tmp/642280217/src/github.com/influxdata/influxdb/tsdb/store.go:607:6: type notUsed is unused (U1000)
```

**Comment by hercules-influx** [comment]
During a run of [megacheck](https://github.com/dominikh/go-tools) the following issues were discovered:
```/tmp/549811851/src/github.com/influxdata/influxdb/tsdb/store.go:607:6: type notUsed is unused (U1000)
```

**Pull request closed without merging**
